### ISSUE TITLE
Ente desktop app keeps crashing with face recognition

### ISSUE THREAD

**Issue by virtual-thread** [ente-io/ente#1014]
### Description

Ente desktop app on windows keeps crashing when I enable face recognition.
[ente.log](https://github.com/ente-io/ente/files/14558035/ente.log)

### Version

1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
Closing this since all these edge cases have been fixed. With the recent versions 1.7.7 etc, ML in the desktop app has reached stability.
