### ISSUE TITLE
[Web] Change layout

### ISSUE THREAD

**Issue by OliDMX** [ente-io/ente#108]
I got like 20 2-Factors+ and the webpage is so similar with the App, that its kinda annoying to scroll all the way down.
Also every time i add a new 2 Factor, it just makes the Webpage longer. You could make multiple Tiles next to eachother, so you can have everything on 1 Page without scrolling infinitively when you want to get an auth code.
![image](https://user-images.githubusercontent.com/96055910/235086835-ea9b94de-2172-40b1-88a4-ecc8db5341fb.png)
So if you would move the first auths to the left, make another row with the next one and the search bar in the top right corner, it would be pretty good i think

**Comment by OliDMX** [comment]
![image](https://github.com/ente-io/auth/assets/96055910/e91102a9-4fc2-40ce-80e5-78733a993118)
For a few days it changed to fullscreen, now sadly its just 2 rows. Could you check it?
I appreciate it, thank you!

**Comment by mnvr** [comment]
Reopening, seems to have been some regression (See https://github.com/ente-io/photos-web/pull/1309#issuecomment-1954173647)

**Comment by vishnukvmd** [comment]
Should be fixed now. Please reopen if it isn't!
