### ISSUE TITLE
web not building

### ISSUE THREAD

**Issue by overflo23** [ente-io/ente#1085]
### Description

README.md states:

## Building from source

Fetch submodules

```sh
git submodule update --init --recursive
```

**works**

Install dependencies

```sh
yarn install
```

**fails**
user@host:~/ente/web$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

....

### Version

current github version

### What product are you using?

Ente Photos

### What platform are you using?

Web - Firefox

**Comment by overflo23** [comment]
had a very old yarn in venv :(

**Comment by mnvr** [comment]
> had a very old yarn in venv :(

:) Great, I assume this is sorted now, closing.
