### ISSUE TITLE
Ente down

### ISSUE THREAD

**Issue by ajsteele** [ente-io/ente#1120]
### Description

I don't seem to be able to access Ente and it seems to be an issue with the server or the connection. Thumbnails and photos don't load in the app, web login is intermittently down, shared gallery links give a 404 error and once I got a Cloudflare error when trying to load via the web… I've tried this on multiple different internet connections so I don't think it's a problem on my end.

**Comment by mnvr** [comment]
Hey @ajsteele, this should be fixed now. We were / are under a DDoS attack, but we've put up mitigations in place (and are also adding more).
