### ISSUE TITLE
Ente tries to upload csv files

### ISSUE THREAD

**Issue by I-I-IT** [ente-io/ente#1131]
### Description

While Ente Photos obviously only supports image files, it doesn't automatically put .csv files in the unsupported category.Instead it tries to upload and put it into the failed uploads batch. If you wonder, why I had .csv files, this is due to a Youtube Takeout.

![Screenshot (10)](https://github.com/ente-io/ente/assets/78900789/27f5e65a-533a-4458-9afb-2d11c45c8f2b)

.

### Version

v 1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Sometimes, the full file name doesn't reflect the correct type of the file. The app tries to identify the correct mimeType of the file, and discard it if it's not supported.
