### ISSUE TITLE
Ente Auth seems to fail at importing codes from files created using Windows

### ISSUE THREAD

**Issue by 0xedward** [ente-io/ente#1142]
### Description

Under `Data` ->  `Import codes` -> `Plain text`, the dialog box says the following `"The codes can be separated by a comma or a new line"`, but when importing a file with `\r\n` characters to indicate a newline, the import service only manages to import the first line of the file and fails to import the rest of the file.

Unfortunately, I haven't gotten a chance to dig deeper into the code to validate this behavior is a bug rather than something unique to my environments.

### Version

v2.0.41

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - FDroid

**Comment by prateekmedia** [comment]
@0xedward Did you literally put "\r\n" characters instead of inserting new lines? Asking this because I am not able to reproduce the same.

Here is a sample Plain text file for reference:
```yaml
otpauth://totp/a:a?algorithm=SHA1&digits=6&issuer=a&period=30&secret=a
otpauth://totp/b:b?algorithm=SHA1&digits=6&issuer=b&period=30&secret=b
otpauth://totp/c:c?algorithm=SHA1&digits=6&issuer=c&period=30&secret=c
otpauth://totp/d:d?algorithm=SHA1&digits=6&issuer=d&period=30&secret=d
otpauth://totp/e:e?algorithm=SHA1&digits=6&issuer=e&period=30&secret=e
```

**Comment by prateekmedia** [comment]
Still I have fixed it and now you can use \r or \n or both together to indicate a line break or in case Windows messes up the line breaks.
Commit:  dd0678d3d0f15bc5b3885e834a45dc0979b6a762
