### ISSUE TITLE
Image switcharoo bug

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/ente#1158]
[Moved from Discord]

### Description

Just shared 2 images from signal to ente and now they are doing weird things

Only image 1 is shown in the album, and when I click the thumbnail of image 1 it shows image 2.

This persists through a restart
Note that I don't have a WiFi ATM so they haven't synced yet.

Device: pixel 6a
OS: grapheneos 2024022600

### Version

v0.8.64

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by TAG-Epic** [comment]
Seems like one of the images doesn't even save :/ 
Also also happens with WiFi so that isn't the issue.

**Comment by vishnukvmd** [comment]
Could you please reproduce the issue once and share logs with support@ente.io?
