### ISSUE TITLE
Ente Photo Not Deleting Deleted Photos on S3

### ISSUE THREAD

**Issue by ching-kuo** [ente-io/ente#1208]
### Description

Environment: self-hosted with external S3 (Ceph rgw)

config for S3
```
s3:
  b2-eu-cen:
    key: xxxx
    secret: xxxx
    endpoint: s3.xxxx.yyyy
    bucket: ente
    region: "default"
  use_path_style_urls: true
```

From logs I can see that it did tries to clean up deleted files, but in S3 the files remain there and not deleted. I couldn't find any errors on unable to delete files. Any ideas how to proceed forward with debugging?

```
| INFO[28199]file.go:599 CleanupDeletedFiles Cleaning up deleted files                                                                                                           │
│ INFO[28199]healthcheck.go:66 PerformHealthCheck Performing HC                                                                                                                  │
│ INFO[28199]trash.go:120 func1 cron run finished                             flow=trash_collection id=39577e5c-ace8-4ae4-a7f2-ff74260710b0 items_processed=0                    │
│ INFO[28199]trash_file_metadata.go:67 DropFileMetadataCron no pending entry                              cron=dropTrashedFileMetadata                                           │
│ INFO[28200]object_cleanup.go:132 removeUnreportedObjects Removing unreported objects                   task=remove-unreported-objects                                          │
│ INFO[28200]object_cleanup.go:152 removeUnreportedObjects Removed 0 objects                             task=remove-unreported-objects
```

The files still exists

```bash
s3cmd ls s3://ente/1580559962386439/
2024-03-25 18:28        98485  s3://ente/1580559962386439/10af9ad1-5f09-478c-8129-f71e8a4528d7
2024-03-25 18:28      7924344  s3://ente/1580559962386439/919e6810-0f35-4a7e-a0ca-d1e132871c11
2024-03-25 18:28      8715374  s3://ente/1580559962386439/ef6818cc-e0dd-4454-8193-45c99544b540
2024-03-25 18:28        91218  s3://ente/1580559962386439/f5fcc334-fc77-4778-b811-d00d0a359477
```

### Version

main branch

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by mnvr** [comment]
p.s. for issues around self hosting, please try to either ask in the GitHub discussions, or in the #self-hosting channel in our Discord. I hope you don't mind!

---

The actual deletion of the underlying S3 object happens after 45 days - you can tweak this on your self hosted setup using this - https://github.com/ente-io/ente/blob/main/server/pkg/repo/queue.go#L24

> Note that if you're also using the compliance lock feature, then this time has to be more than the compliance lock duration.

This should solve your query, I'll close this issue for now. But please do ask if I misunderstood something. Thank you!
