### ISSUE TITLE
no data showing bug

### ISSUE THREAD

**Issue by MAAB-FW** [ente-io/ente#1216]
### Description

After updating the app no ​​data was showing. It said to import new data but still logged in, I just updated the app. I thought where did the data go!? Login to the website and see that the data is correct. After logging out again in the app, it shows the data after logging in

### Version

2.0.46

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by vishnukvmd** [comment]
Hey, we changed the directory where we're storing our data, and this is likely to happen again **one more time**, when we make the public release. It won't after that (hopefully!).

Like you already figured out, logging out and logging back in will set things right. Sorry about this!
