### ISSUE TITLE
CLI ente export breaks with illegal base64 

### ISSUE THREAD

**Issue by PichlerD** [ente-io/ente#1237]
### Description

In the initial phase of exporting data via ente cli it synces metadata files
` 2024/03/28 23:49:26 Sync files metadata from album Images`

from about the 5th album in out of many I'm getting an exception and it aborts.
```
2024/03/28 23:49:28 Error fetching files: invalid data: illegal base64 data at input byte 0
Error syncing account xxx@xxx.com: invalid data: illegal base64 data at input byte 0
```

This happens before any actual photo has been synced to the local drive for me.

The album in question and basically all albums have been uploaded via google takeout if that matters.

### Version

ente-cli-v0.1.12-linux-amd64

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Linux

**Comment by ua741** [comment]
Hey @PichlerD,

Thank you for sharing the error details. From the log, it looks like there was an error during base64 decoding for some encrypted data. In order to debug it further, I need additional details. I have improved the logs and published a new version of the CLI (v0.1.13).

Can you please upgrade and share the new error here or over email at support@ente.io?

**Comment by PichlerD** [comment]
```
 2024/03/29 12:43:59 Error fetching files: failed to decrypt metadata for file 34381366: invalid base64 data -: illegal base64 data at input byte 0
Error syncing account xxx@xxx.com: failed to decrypt metadata for file 34381366: invalid base64 data -: illegal base64 data at input byte 0

```
This is what I see with the new version

**Comment by ua741** [comment]
Thank you for sharing the log. Can you please retry now? We have fixed some inconsistencies related to deleted files, which were causing this issue.

**Comment by PichlerD** [comment]
Seems to pass now, I'll report back once I did a full export
