### ISSUE TITLE
Fiirefox account not supported

### ISSUE THREAD

**Issue by brownhamer** [ente-io/ente#1264]
### Description

When trying to setup 2FA with my Firefox sync account it does not work. The QR code scans and codes are generated. However the Firefox sync keeps reporting that the code is incorrect.

### Version

v2.0.41

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows

**Comment by vishnukvmd** [comment]
Could you please confirm that the device time is correct?

**Comment by brownhamer** [comment]
Yep, device time is ok, both smartphone and computer.

**Comment by brownhamer** [comment]
Not sure what happened. Tried again today and it works fine now. Closing the issue.
