### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ente-io/ente#1279]
### Description

https://monitor.f-droid.org/builds/log/io.ente.auth/250#site-footer

ah, let me fix the paths

fail: [io.ente.auth_250.log.gz](https://github.com/ente-io/ente/files/14824035/io.ente.auth_250.log.gz)

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/6156665e9efa547f744dcb0441d7fc8a59e83621

fail appears related to https://pub.dev/packages/smart_auth  but that is non-FOSS as it depends on Google proprietary libs, per https://github.com/Tkko/flutter_smart_auth/blob/main/android/build.gradle#L56-L57

in the log see lines 397-400 where the non-FOSS deps are removed, and that cleaning might trigger the fail

**Comment by prateekmedia** [comment]
@licaon-kter Weirdly this smart_auth is part of [pinput](https://pub.dev/packages/pinput), which has been part of both auth and photos from long time but it never failed before to best of my knowledge.

**Comment by licaon-kter** [comment]
for 0.8.81 Flutter was not bumped: https://github.com/ente-io/ente/tree/fdroid-v0.8.81/mobile/thirdparty :(

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6627585421#L919

**Comment by vishnukvmd** [comment]
Sorry, and thank you!

Have just pushed [fdroid-v0.8.82](https://github.com/ente-io/ente/releases/tag/fdroid-v0.8.82).

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/cf95d2990afc49d5d193c16ace0eb8b77b63b93b

**Comment by licaon-kter** [comment]
can we reopen?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7003742451#L835

**Comment by licaon-kter** [comment]
fixed in 3.0.7 https://gitlab.com/fdroid/fdroiddata/-/commit/2aa6cc7205e14e0d80359a21457223811bf0f8f5
