### ISSUE TITLE
Proposal for Funding Mechanism to Support ente Auth Development

### ISSUE THREAD

**Issue by iAnonymous3000** [ente-io/ente#128]
Considering the effort needed to maintain and enhance ente Auth, I propose establishing funding mechanisms to support its development.

Options include:

Platforms like [Open Collective](https://opencollective.com), GitHub Sponsors, or something like that for donations and sponsorships.

Implementing these can foster long-term sustainability and success of ente Auth.

**Comment by mnvr** [comment]
This is done now, we have enabled [GitHub sponsorships](https://github.com/sponsors/ente-io)! Thank you @iAnonymous3000 for the suggestion 🙏

This is maybe a good time to reiterate to the other folks who end up reading this - the absolute best way to support us is to get a paid subscription to Ente Photos. But if you feel like contributing to the project over and beyond, you now also have the option to sponsor.

Thank you everyone ❤️
