### ISSUE TITLE
Use without backups requires biometic auth?

### ISSUE THREAD

**Issue by digitalfredy** [ente-io/ente#1293]
### Description

First thanks for this great app,

A user in my organization tried to add ente auth without account ("Use without backups") and found that is not possible to use this option because that cell phone does not have fingerprint reader.

I'm attaching this video to report this bug:

https://github.com/ente-io/ente/assets/1372919/764df420-c72d-435d-b915-e0876df1f835

Expected behavior:

No discrimination against cheap phones :stuck_out_tongue_closed_eyes: 

Extra info:
- Device: Motorola E13 (motoe13) 
- Android version: 13
- Ente Auth: 2,0,41

### Version

2,0,41

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by vishnukvmd** [comment]
Hey, thanks for the feedback! The request is already being tracked here: https://github.com/ente-io/ente/discussions/490

I'll close this in favor of that for now, but please feel free to re-open if you think I missed something.

**Comment by mnvr** [comment]
> No discrimination against cheap phones 😝

@digitalfredy hehe 😝

**Comment by MagicFab** [comment]
This also prevents use on *some* Windows systems : worked fine on a desktop, didn't (and reported the same error) on a laptop.
