### ISSUE TITLE
[Auth Desktop] Lockscreen can't be set up

### ISSUE THREAD

**Issue by taivlam** [ente-io/ente#1316]
### Description

The lockscreen can't be set up on ente Auth for desktop when using this UI path: Settings hamburger menu > Security > Lockscreen.

When I try to activate the lockscreen (similar to the local app lock UI on the mobile for Android), I receive a pop up that says:

> To enable lockscreen, please setup device passcode or screen lock in your system settings.

The toggle turns itself off, and nothing else can be done for this option.

I'm aware that the way that lockscreens work on Android/iOS (i.e., mobile platforms) is different than desktop when it comes to low-level implementations; and not all laptops have a consistent implementation of fingerprint scanners, though I still wanted to bring this up after I installed it.

## System details
* Manjaro Unstable
* Installed ente Auth Desktop from the [AUR](https://aur.archlinux.org/packages/ente-auth-bin) (the `ente-auth-bin` package)

### Version

2.0.50-1

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by vishnukvmd** [comment]
Closing in favor of https://github.com/ente-io/ente/discussions/1016

**Comment by ericsayles** [comment]
I'm still experiencing this issue on the Windows 10 desktop.
