### ISSUE TITLE
[ente Auth Desktop] Option to manually change UI theme is missing

### ISSUE THREAD

**Issue by taivlam** [ente-io/ente#1317]
### Description

There is currently no option to manually change the UI theme between light and dark in the ente Auth Desktop application.

This following section in the settings for adjusting the theme is missing: Settings hamburger menu > Theme.

That UI path in the settings exists on ente Auth on Android (version 2.0.41 from F-Droid), which lets the user change between light and dark mode.

Below is a screenshot:
![screenshot1](https://github.com/ente-io/ente/assets/47955724/45289053-8ace-496a-b9b8-485051c91db4)

## System details
* Manjaro Unstable
* Installed ente Auth Desktop from the [AUR](https://aur.archlinux.org/packages/ente-auth-bin) (the `ente-auth-bin` package)

### Version

2.0.50-1

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by JRuedas** [comment]
The option to switch the theme to light/dark is still missing on the latest version `3.1.3`

**Comment by ua741** [comment]
In the upcoming version > 4.1.5, you will see option to switch theme for Windows & Linux.
