### ISSUE TITLE
[Photos] Background music does not pause when watching video

### ISSUE THREAD

**Issue by TomsDex** [ente-io/ente#1350]
### Description

Reproduction steps:
1. Play music in the background (I was using Spotify).
2. Open ente photos and play a video.

Expected outcome:
The music in the background pauses and only the video audio plays.
Actual outcome:
Both the music and the video audio play over each other.

This is on a Samsung S22 Ultra, using ente downloaded from GitHub via Obtainium.

### Version

v0.8.75

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by vishnukvmd** [comment]
Thanks for reporting this!

We could use [audio_session](https://pub.dev/packages/audio_session) to pause any ongoing streams before starting the video playback (and undo this action when the video is paused).
