### ISSUE TITLE
[Auth] Appimage doesn't launch

### ISSUE THREAD

**Issue by Brendovisk** [ente-io/ente#1361]
### Description

When I try to run the Appimage on my linux system (Arch with gnome 46), it gives me the following error:

``
error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
``

### Version

2.0.50

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by vishnukvmd** [comment]
cc @prateekmedia

**Comment by prateekmedia** [comment]
Duplicate of #472
