### ISSUE TITLE
App Errors out on Windows ARM

### ISSUE THREAD

**Issue by TommyTran732** [ente-io/ente#1374]
### Description

Photos just errors out when after I finished installing it on Windows ARM:

<img width="1511" alt="Screenshot 2024-04-08 at 05 37 08" src="https://github.com/ente-io/ente/assets/57488583/a532d916-22c0-4599-ac4a-6d4dd9c8b638">

### Version

v1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
I think I've found the reason, and have fixed it here - https://github.com/ente-io/ente/pull/1405. I'm unable to test because I don't have a Windows ARM machine at hand. So if this doesn't get fixed when we do the next release of the desktop app, please reopen! Thank you.

**Comment by mnvr** [comment]
@TommyTran732 Can you try installing the Microsoft VC++ redistributable runtime from here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

That might fix the error already (unless it is an ARM specific issue, in which case you'll need to wait for the next version of Ente with the fix I made previously)

**Comment by TommyTran732** [comment]
> @TommyTran732 Can you try installing the Microsoft VC++ redistributable runtime from here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
> 
> That might fix the error already (unless it is an ARM specific issue, in which case you'll need to wait for the next version of Ente with the fix I made previously)

Hi,

Installing VC++ ARM fixed it :)
