### ISSUE TITLE
Ente auth-v2.0.54 does not worked on Ubuntu 22.04

### ISSUE THREAD

**Issue by dtantono** [ente-io/ente#1393]
### Description

I understand that this release note suppose to fix libffi issue for Appimage. But, it still does not worked

<img width="880" alt="image" src="https://github.com/ente-io/ente/assets/29157187/3e2b1059-e817-403c-9d0b-383b40eb2417">

### Version

2.0.54

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by vishnukvmd** [comment]
Closing in favor of #472.
