### ISSUE TITLE
[Feature Request] : Ability to selfhost auth server 

### ISSUE THREAD

**Issue by fedonr** [ente-io/ente#141]
Something like Bitwarden (Vaultwarden), where I can add a link in App and host my own instance of ente Auth Server via Docker.

**Comment by WardPearce** [comment]
> Something like Bitwarden (Vaultwarden), where I can add a link in App and host my own instance of ente Auth Server via Docker.

Would love to know if documentation around this is planned or out of scope for the project?

**Comment by vishnukvmd** [comment]
Hey, we'd love to provide a self hosted alternative for both Photos and Auth (our server is a monolith). We're currently constrained by bandwidth. Once we've engineers who can help maintain a community around a self-hosted variant, we'll open source our servers. Will keep this issue open until then.

**Comment by WardPearce** [comment]
> Hey, we'd love to provide a self-hosted variant for both Photos and Auth (our server is a monolith). We're currently constrained by bandwidth. Once we've engineers who can help maintain a community around a self-hosted variant, we'll open source our servers. Will keep this issue open until then.

awesome, understandable as developing with self-hosting in mind does add a bit of overhead.

**Comment by fedonr** [comment]
That's an awesome news, thanks a lot for the revert.

**Comment by rainyskye** [comment]
Hey, just reaching out to see if there is any updates on this? I'm sure even a community effort could be used towards getting something put together, as far as I can see at the moment none of the server side components are open sourced?

**Comment by Gurkengewuerz** [comment]
Any updates on this?

**Comment by bdonvr** [comment]
Man I've been holding out on a self hosted Authy replacement with mobile and desktop apps. This would be incredible

**Comment by NightMachinery** [comment]
Related:
- https://ente.io/blog/open-sourcing-our-server/

**Comment by tarunx** [comment]
This is absolutely incredible ! More people will find our about this beautiful product you have created. Is there any plan add a feature to mobile apps so they can point to custom self-hosted server URLs?

**Comment by vishnukvmd** [comment]
Closing this in favor of the discussion @ https://github.com/ente-io/ente/discussions/504.
