### ISSUE TITLE
JavaScript error after (sucessful) payment

### ISSUE THREAD

**Issue by jan-glx** [ente-io/ente#1440]
### Description

After subscribing and entering payment details for payment via sepa direct in the windows desktop app v1.6.63, ente shows an error "A JavaScript error occurred in the main process" (see screenshot)
![Screenshot 2024-04-14 162526](https://github.com/ente-io/ente/assets/1266815/78be18ff-af88-4fa3-9acc-56ae3d5063a6)

After acknowledging the error the app shows the ente website instead of the app (View->Reload or reopening the window from the taskbar does not help) 
![Screenshot 2024-04-14 162611](https://github.com/ente-io/ente/assets/1266815/eb74ac8c-9155-4963-b09c-1680a84fa8fb)

Did not try to reproduce (for obvious reasons), happy to privately share the log. 

### Version

v1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
Thanks for reporting. Does restarting the app get you out of this state?

**Comment by mnvr** [comment]
Indeed, I've found an issue in our payments portal. I've fixed it now (https://github.com/ente-io/ente/pull/1447), and now the redirect back to the desktop app should work fine. Thank you for the report!
