### ISSUE TITLE
Import from Aegis authenticator fails when there are Steam Guard entries

### ISSUE THREAD

**Issue by fourilent** [ente-io/ente#1469]
### Description

When trying to import an Aegis export file with Steam Guard entries, the application throws an error: "Could not parse the selected file. ....". I verified this by removing Steam Guard entries from my Aegis installation and re-importing an export, which worked.

Steps to reproduce:
1. Add a Steam entry into Aegis Authenticator
2. Export the .JSON file
3. Attempt to import the .JSON file in Ente Auth
4. Get the error

### Version

v2.0.54

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by vishnukvmd** [comment]
Thanks for sharing! For now I'll close this in favor of https://github.com/ente-io/ente/discussions/1038. Feel free to reopen if I've missed something.
