### ISSUE TITLE
Ente CLI (auth): error decrypting data failed to decrypt data: invalid tag

### ISSUE THREAD

**Issue by pashynskykh** [ente-io/ente#1517]
### Description

Hi there,

I'm trying to decrypt my backup from Ente Auth using Ente CLI for GNU/Linux (amd64) and it fails with the following error:
> error decrypting data failed to decrypt data: invalid tag
> Please check your password and try again

I am using v0.1.13, but the same problem with v0.1.12.

The password is 100% correct (copied from the password manager and also tried to enter it manually) and I was able to import this backup into the mobile app without any problems.

### Version

v0.1.13

### What product are you using?

Ente CLI v0.1.13

### What platform are you using?

Debian Bookworm (amd64)

**Comment by pashynskykh** [comment]
I just tried to decrypt from MacOS (arm64) - same error. Looks like the problem is not platform specific.

**Comment by pashynskykh** [comment]
@ziadoz backups are fine, I managed to restore them successfully on another device. There's something wrong with the CLI tool, as it can't decrypt backups created by recent versions of Ente Auth. 

Anyway, that's clearly a critical issue.

**Comment by ziadoz** [comment]
> However, this could be a critical issue for someone.

Yeah, it is for me, as I backup and verify using the CLI tool.

**Comment by RossPatterson** [comment]
I hate to "_me too_" an issue, but chiming in here to add that v0.1.13 on Windows fails exactly as the previous reporters have said.

**Comment by ua741** [comment]
Apologies for dropping the ball on this issue. We have released a potential fix in the latest version (v0.1.14).

**Comment by pashynskykh** [comment]
v0.1.14 works for me on the M1 Mac. Will check on a Debian machine later.

**Comment by ziadoz** [comment]
I've tried v.0.1.14 here and it works again. Thanks for fixing this.
