### ISSUE TITLE
Can not start Ente Auth

### ISSUE THREAD

**Issue by jbugel-lol** [ente-io/ente#1550]
### Description

I was trying to install Ente Auth to get to my 2fa codes.
But I was encountering following issue:
There were 4 missing dll files, reinstalling did not fix
![image](https://github.com/ente-io/ente/assets/115107409/30d9aa00-4c5b-4af3-8bcd-f794cde6613f)
![image](https://github.com/ente-io/ente/assets/115107409/b60dc113-26d8-4fd2-9e9b-a3a0e3f06219)
![image](https://github.com/ente-io/ente/assets/115107409/7076619f-18d0-47da-926f-2f2131d15603)
![image](https://github.com/ente-io/ente/assets/115107409/163e13b1-bc68-4811-96db-850bfe367baa)

### Version

2.0.54+254

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by Shaddow798** [comment]
I initaly got those same dll errors, when trying to install ente auth on a fresh install of windows 10, I was able to fix that issue by installing the visual C++ runtimes and that fixed that issue, although I still cannot log in.

[](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by vishnukvmd** [comment]
@jbugel-lol could you confirm if installing Visual C++ runtime like @Shaddow798 suggested fixes your issue?

> I still cannot log in.

@Shaddow798 could you share more details? What's the error you're seeing?

**Comment by jbugel-lol** [comment]
@vishnukvmd yes, this works, but like they, i also can not login

**Comment by vishnukvmd** [comment]
@jbugel-lol Could you please share more details about the error you're seeing when you try to login?

**Comment by jbugel-lol** [comment]
latest beta fixed it but iirc it was some server error

**Comment by spotter226** [comment]
I did a clean install of Windows 11 24H2 and at the time of opening Ente Auth I get the error VCRUNTIME140_1.dll. I have already installed the Visual C++ packages “Visual Studio 2015, 2017, 2019, and 2022” but could not solve it. If someone kindly can help me out. Thank you.

**Comment by spotter226** [comment]
> I initaly got those same dll errors, when trying to install ente auth on a fresh install of windows 10, I was able to fix that issue by installing the visual C++ runtimes and that fixed that issue, although I still cannot log in.
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I did a clean install of Windows 11 24H2 and at the time of opening Ente Auth I get the error VCRUNTIME140_1.dll. I have already installed the Visual C++ packages “Visual Studio 2015, 2017, 2019, and 2022” but could not solve it. If someone kindly can help me out. Thank you.
