### ISSUE TITLE
[Auth] New icons are not appearing

### ISSUE THREAD

**Issue by ialexanderbrito** [ente-io/ente#1627]
### Description

New icons are not appearing, after it was updated some icons are not appearing in the auth. The ones I noticed in my account were
- ConfigCat
- Habbo
- Mercado Livre
- SendGrid

![image](https://github.com/ente-io/ente/assets/36086408/73103c22-7e06-4580-8b21-50a257c9f68b)

### Version

v2.0.56

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows, Desktop - macOS, Web - Edge

**Comment by vishnukvmd** [comment]
The code seems to be working as intended, but looks like something is up with the SVG icons :(

**Comment by maujavier91** [comment]
Any way to add alternative names for icons? Mercado Livre is the brazilian name but in spanish is MercadoLibre (actually this is the official name, since the company is argentinian, but it does have the localized name in brazil)

**Comment by ialexanderbrito** [comment]
From what I've seen, to add alternative names you need to use `altNames` so you can add more than one name. Sorry for the Mercado Livre mistake, I had forgotten that it has two names

**Comment by fco-pires** [comment]
I can confirm that the Mercado Livre icon does not appear, even in version 3.0.4.

**Comment by clrizzi** [comment]
Yes. I also have the same problem. The [Mercado Livre](https://www.mercadolivre.com.br/) icon does not appear.

**Comment by ialexanderbrito** [comment]
I just sent a PR that should correct the Mercado Livre icon error and I also added the alternative names so that the icon also appears. Everything should probably be working in the next version, whichever is released.

The PR number is #1981

**Comment by clrizzi** [comment]
> I just sent a PR that should correct the Mercado Livre icon error and I also added the alternative names so that the icon also appears. Everything should probably be working in the next version, whichever is released.
> 
> The PR number is #1981

Thanks, @ialexanderbrito 

I just update the Auth to the new version and the icon "Mercado Livre" appeared, but in a solid yellow block on both themes: Dark and Light.

**Comment by ialexanderbrito** [comment]
@clrizzi Make sure you are on the latest version that was released, as I also had this problem in version 3.0.4, the latest version 3.0.7 came out yesterday and it was fixed

**Comment by clrizzi** [comment]
> @clrizzi Make sure you are on the latest version that was released, as I also had this problem in version 3.0.4, the latest version 3.0.7 came out yesterday and it was fixed

Yes... I'm on the 3.0.7 version.

**Comment by maujavier91** [comment]
@ialexanderbrito I see that mercadolibre altNames were added but it doesn't appear to work for some of the alt names, the icon only appears if the name is "MercadoLivre" or "Mercado Livre", but not the spanish version "MercadoLibre" or "Mercado Libre".
