### ISSUE TITLE
userauth and request_logger is logging extra information

### ISSUE THREAD

**Issue by ahxxm** [ente-io/ente#1693]
### Description

I tried self-hosting a vanilla server, these are logs I'm seeing

2fa code is logged after generation, [code pointer](https://github.com/ente-io/ente/blob/ca9190045e51664051971d5750ac07b3c8d8a0a7/server/pkg/controller/user/userauth.go#L156)
```
museum-1           | INFO[0330]userauth.go:156 verifyEmailOtt Valid ott (app: photos) for al...= are 180143
```

Being thankful to avoid configuring email or look into db, I used the code to the next step, key generation

then private key was intercepted and logged by `request_logger`, maybe `/users/attributes` can be added to [shouldSkipBodyLog](https://github.com/ente-io/ente/blob/ca9190045e51664051971d5750ac07b3c8d8a0a7/server/pkg/middleware/request_logger.go#L34) as well?
```
museum-1           | INFO[0367]request_logger.go:100 func1 outgoing                                      client_ip=100.92.249.73 client_pkg=io.ente.frame client_version=0.8.94 h_latency=2.768339ms latency_time=2.768339ms query= req_body={"keyAttributes":{"kekSalt":"ymLzoS9cX28E0hsx5VbKWg==","encryptedKey":"5TkZ3AqTDcp7Maizh8NT4Gyg2aeneUlUIcpAbYnzV7cxRwrqx0PBCgxxSPl9RIgJ","keyDecryptionNonce":"FH67ZoJihN+9vgLN3l0ZIuyuas9rvquI","publicKey":"c3Ib5VPaX1BkoToI826zQkDNz/LISWBnQqeIQbCrRn8=","encryptedSecretKey":"CLQr+QI+oMomoj8VHf/MYkYVv6SvUjPDqnp64XURW/k4oIfqLwwT9VOSpPjknWv9","secretKeyDecryptionNonce":"AAGzrFGTNWbpqv32UvTayQo6sJ5QGbCO","memLimit":1073741824,"opsLimit":4,"masterKeyEncryptedWithRecoveryKey":"kNQl8eRsIsgNrUaq5oxla5naOYyJvqQrq/47g37Ua9qbbzISGgZ0fczD73SOID+x","masterKeyDecryptionNonce":"lkv6ELmOZxCnEhZBfMkJsFy+paqQZrfy","recoveryKeyEncryptedWithMasterKey":"kMCeJdoiexI4ezF7FKEGezt2uhsc5nIL0mD4+cF3r/7SgfsMRk9EfEGsSj5uPLjl","recoveryKeyDecryptionNonce":"5xp0pngaLfxjqEyje+HVUvyIX4e0nRhz"}} req_id=2607db6f-72d7-4492-a486-8b5a7b18bc7f req_method=PUT req_uri=/users/attributes status_code=200 ua=CFNetwork/1.0 Darwin/23.4.0 (iPhone iOS/17.4.1) user_id=1580559962386438
```

### Version

main branch as of ca9190045

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by ua741** [comment]
As the keys are encrypted, there's no harm in logging them. The other skip log was to reduce the log volume by size. Those logs were for encrypted embedding, which can always be regenerated if lost.

As these logs are not really secret, and they can help in debugging or recovering data if need be, we will keep them enabled.
