### ISSUE TITLE
Casting crash

### ISSUE THREAD

**Issue by brog-io** [ente-io/ente#1701]
### Description

When casting with auto pair, it connects to my Chromecast HD. But the Ente app turns black. After a few images show up on my Chromecast, It stops and goes back to Google TV. 

I've tried multiple times and I always get the same result. This didn't happen when manually pairing Ente and using a browser on my TV

### Version

0.8.94

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by maccaches** [comment]
I've had the same issue using a Pixel 6 Pro with a Chromecast with Google TV on the same version of Ente Photos.

**Comment by vishnukvmd** [comment]
@maccaches could you please confirm if it was the mobile app that was crashing, or the app on Chromecast, or both? Thanks, and sorry about this!

**Comment by brog-io** [comment]
For me, the app doesn't crash on my phone, but it does turn black. It closes on Google TV though. I'll check the logs this evening and post them here

**Comment by brog-io** [comment]
Here are my logs

![ente-logs-2024-May-13-16-10.zip](https://github.com/ente-io/ente/files/15297238/ente-logs-2024-May-13-16-10.zip)

**Comment by maccaches** [comment]
@vishnukvmd My screen also turns black on my phone, however my Chromecast doesn't respond at all when I click on it in the Ente Photos app.

**Comment by lesydimitri** [comment]
I'm seeing similar behaviour here. When trying to cast an album, the album starts playing as a slideshow on the chromecast and the Android app goes completely black. The only way to get out of that black screen is to force close Ente Photos.

Phone Model: Pixel 5
OS: GrapheneOS 2024052100
Ente Photos Version: 0.8.94

**Comment by turbovan** [comment]
Trying to cast an album from Pixel Pro 7 to Nvidia Shield Pro. Shield shows PIN code with instructions to enter the code, ente app on phone goes black and unresponsive, nowhere to enter PIN code. No photos are shown.

**Comment by ua741** [comment]
This should be fixed in the latest version of the app.
