### ISSUE TITLE
Missing shared library libffi.so

### ISSUE THREAD

**Issue by utilisateuralpha** [ente-io/ente#1734]
### Description

Good morning.

I'm on Linux Mint LMDE6. When I run the ente-auth application in AppImage version, I receive the following error:

./ente_auth: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory

Please add libffi.so.7 to the application. The AppImage package should contain all the elements necessary for proper execution on any Linux distribution.

Thank You

### Version

appimage 2.0.54

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by arran4** [comment]
I got the same error on Gentoo.. `dev-libs/libffi-3.4.4-r4` is already installed too:
```
% chmod +x ente-auth-v2.0.54-x86_64.AppImage 
arran@arran-desktop:/home/arran/Downloads 17435 
% mv ente-auth-v2.0.54-x86_64.AppImage ~/.local/bin/
arran@arran-desktop:/home/arran/Downloads 17437 
% zsh: command not found: auth
cd ~/.local/bin/
arran@arran-desktop:/home/arran/.local/bin 17438 
% mv ente-auth-v2.0.54-x86_64.AppImage auth
arran@arran-desktop:/home/arran/.local/bin 17440 
% auth
./ente_auth: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
% sudo emerge -va dev-libs/libffi
Password: 

 * IMPORTANT: 4 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 3.63 s (backtrack: 0/20).

[ebuild   R    ] dev-libs/libffi-3.4.4-r4:0/8::gentoo  USE="-debug -exec-static-trampoline -pax-kernel -static-libs -test" ABI_X86="32* (64) (-x32)" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] ^CInterrupted.

```

**Comment by prateekmedia** [comment]
The new version should work, let me know if you are still facing it!

**Comment by arran4** [comment]
It seems to. Thanks!
