### ISSUE TITLE
tag feature error

### ISSUE THREAD

**Issue by michaelsara** [ente-io/ente#1786]
### Description

When attempting to apply two tags to a single captcha, the tag search functionality fails with the message, "We were unable to parse 2 codes."

Even after removing all tags, the error persists.

### Version

3.0.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Could you please perform the following steps and share the logs with us:

- Enable logs (Settings -> General -> Crash & Error Reporting).
- Kill/swipe out the app, and open it.
- Go to Settings -> Support -> Report a Bug.

Also, are you able to view the code on the web (https://auth.ente.io)?

**Comment by michaelsara** [comment]
> Could you please perform the following steps and share the logs with us:
> 
> * Enable logs (Settings -> General -> Crash & Error Reporting).
> * Kill/swipe out the app, and open it.
> * Go to Settings -> Support -> Report a Bug.
> 
> Also, are you able to view the code on the web (https://auth.ente.io)?

An email containing the log has been sent.
On the web page, some captcha codes are also failing to display, whereas they are displayed properly in the version v2 app.

**Comment by prateekmedia** [comment]
Fixed in latest version!
