### ISSUE TITLE
Import from Vaultwarden not working

### ISSUE THREAD

**Issue by amberflag48** [ente-io/ente#1868]
### Description

Hello,

Not sure if it also happens with Bitwarden, but I'm unable to import json exports from Vaultwarden.

I get 'Could not parse the selected file'

The exported json is not encrypted and only contains logins.

I'm on the latest version of Vaultwarden and ente.

Thanks!

### Version

V3.0.4

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Can you please update to the latest version, and share the logs here or with support @ ente.io.

**Steps to share logs:**

-  Enable Error logging from Settings -> General -> Crash and Error 
- Try importing Vaultwarden export
-  Settings -> Support -> Report a bug

**Comment by ua741** [comment]
Closing this issue. Please feel free to re-open with logs if you are still facing any error.
