### ISSUE TITLE
Auth: TOTP codes for Steam are NOT generated correctly since v3.0.6

### ISSUE THREAD

**Issue by pashynskykh** [ente-io/ente#1980]
### Description

Auth v3.0.6 broke Steam support. App now generates basic TOTP codes instead of Steam alpha-numeric codes.
![IMG_0848](https://github.com/ente-io/ente/assets/14852335/1df6a76f-8ef3-4994-8464-7069b6dfad09)

### Version

v3.0.6

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by ua741** [comment]
Can you copy the secret and add a new entry with Steam as issuer and confirm if it works?

**Comment by pashynskykh** [comment]
> Can you copy the secret and add a new entry with Steam as issuer and confirm if it works?

After creating a new item, it works. Thank you!
