### ISSUE TITLE
Cannot start app or got black screen 

### ISSUE THREAD

**Issue by wiryonolau** [ente-io/ente#2006]
### Description

Cannot start application after updating to 3.0.6, downgrade to 3.0.4 back to normal
No response when calling the application ( no window appear )
But sometime it appear with black screen no content.

OS : Debian 12, install using .deb without error

### Version

v3.0.6

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by ua741** [comment]
Fixed in v3.0.7
