### ISSUE TITLE
Passkeys link in app brings you to 404 page

### ISSUE THREAD

**Issue by ph00lt0** [ente-io/ente#2150]
### Description

When clicking the passkey option in the side menu it opens a page on accounts.ente.io that displays a 404 page. 

### Version

0.8.131

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by brog-io** [comment]
Are you in the Photos Beta?

**Comment by brog-io** [comment]
I think they published it on accident... passkeys aren't released yet. I think it'll be available in the next update though.
