### ISSUE TITLE
Desktop .appimage not working on (K)Ubuntu 24

### ISSUE THREAD

**Issue by schoeeeeeeeeee** [ente-io/ente#2152]
### Description

Hi, I tried to install Ente Auth on Linux (Kubuntu 24) using either the .appimage or the .deb package, but neither worked (there is already an issue for the .deb package however though) 

When I download the .appimage, it opens, but just shows an empty window with no content. I also tried 1 earlier version, that didn't work either (v.3.0.7)
![ente auth empty screen](https://github.com/ente-io/ente/assets/104581805/754b2b61-fd61-4532-9278-78dd8eaa3f0e)

It looks like the only way to get it to work currently on Ubuntu is online in the browser.

Thank you for reading this, and have a nice day 

### Version

v3.0.8

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by prateekmedia** [comment]
@schoeeeeeeeeee Could you share the logs when you run the appimage from the terminal?

**Comment by schoeeeeeeeeee** [comment]
Sure, here they are:
[ente auth appimage log.txt](https://github.com/user-attachments/files/15944162/ente.auth.appimage.log.txt)


I tried with both the latest version and the version I was previously having issues with. both seem to produce an identical log.

**Comment by schoeeeeeeeeee** [comment]
[2024-6-23.txt](https://github.com/user-attachments/files/15944172/2024-6-23.txt)
Here's the log file it produced, in case that helps. But it doesn't mention an error

**Comment by prateekmedia** [comment]
I think the problem is with your keyring, ente auth is unable to unlock it (idk why):
** (ente_auth:15630): WARNING **: 12:26:00.682: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>

**Comment by schoeeeeeeeeee** [comment]
Okay, so I also have another system with Ubuntu 22, and it works fine there. Both the .appimage and the .deb package. Possibly caused by some sort of regression from 22 to 24?

**Comment by prateekmedia** [comment]
I think it's not and it's specific to KDE only cause the app currently don't have functionality to unlock your keyring IIRC. So try to unlock your keyring on Kubuntu first and see if it works.

Keyring is locked when you have automatic login or if you have set different password or setting for it.

I think disabling Kwallet and restarting may help, or try to access a app like firefox which will ask for keyring hopefully and then run ente auth.

**Comment by schoeeeeeeeeee** [comment]
I don't understand, I don't even have Kwallet enabled

**Comment by prateekmedia** [comment]
Could you answer these:
- Do you have a chromium based browser and does it requires you to enter password when first time open after login
- Do you have automatically login without password enabled?

**Comment by schoeeeeeeeeee** [comment]
Sure,
1. No, I don't need to enter my password after login when opening the browser
2. No, I don't have that enabled

**Comment by schoeeeeeeeeee** [comment]
would it help if I ran it on a virtual machine with just Ubuntu 24 (no KDE) to confirm it's caused by KDE?

**Comment by prateekmedia** [comment]
Yes.

**Comment by schoeeeeeeeeee** [comment]
OK, so seems like it is indeed caused by KDE 24, I was able to get it to work on the virtual machine with Ubuntu, no KDE. looks like it's just broken on kubuntu :/ however it works fine in kubuntu 22. any suggestions?

**Comment by prateekmedia** [comment]
Can you see if your system has gnome-keyring present? Basically it is a keyring issue and other gtk apps which are using keyring like Brave browser should also have it (or atheist they would be asking it on launch).

**Comment by schoeeeeeeeeee** [comment]
hmmmm, i don't have that installed. lemme try install it rq…

**Comment by schoeeeeeeeeee** [comment]
Yay, that fixed it! Thank you so much!
