### ISSUE TITLE
Synology Web Account > Invalid QR Code

### ISSUE THREAD

**Issue by RedPeace** [ente-io/ente#2163]
### Description

Hi,

Synology Online Account (not the local NAS account) can be protected with 2FA.
But ente auth display message "Invalid QR Code".

### Version

3.0.8

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Hello,

In the latest app, we are able to scan the QR code and add the account.

P.S. Initially, I was trying to scan a QR code that was just a URL to download the Synology app. On the next screen, I was able to see and scan the MFA QR code.

If you are still facing an issue, please share the QR code either here or with our support team at support@ente.io.
