### ISSUE TITLE
Cached credentials on password change

### ISSUE THREAD

**Issue by ua741** [ente-io/ente#2218]
### Discussed in https://github.com/ente-io/ente/discussions/2176

<div type='discussions-op-text'>

<sup>Originally posted by **ph00lt0** June 17, 2024</sup>
### Description

After changing the password the new password is not working on the webapp when logging in again in the same browser. 

Ente does not clean up the old cached credentials in this scenario causing confusion to the user, who changed the password.

### What product are you using?

Ente Photos, Ente Auth

### What platform are you using?

Web - Chrome</div>

**Comment by mnvr** [comment]
Ref: https://github.com/ente-io/ente/pull/2230

**Comment by mnvr** [comment]
Fixed in https://github.com/ente-io/ente/pull/2230 (for more context, see https://github.com/ente-io/ente/issues/1891#issuecomment-2196341285)
