### ISSUE TITLE
passkeys support for 3rd party password managers

### ISSUE THREAD

**Issue by Vantesh** [ente-io/ente#2275]
### Description

i cant get enth auth to store passkeys to proton pass on either android or windows, it just uses the chrome and windows manager to store the passkeys

### Version

3.0.17

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by brog-io** [comment]
What browser do you use? Most android browsers don't support passkeys for 3rd party password managers yet. 

It should work on Windows though, I also use ProtonPass, so maybe try a different browser

**Comment by Alsisjshsh** [comment]
D
