### ISSUE TITLE
My phone ,desktop and web not syncronise correctly

### ISSUE THREAD

**Issue by muktadir921** [ente-io/ente#2295]
### Description

my android ,pc and web not showing same code they show diffrent codes . and only phone codes are working kindly solve this issue.
email: muktadirhossan921@gmail.com

### Version

latest

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows, Web - Chrome

**Comment by brog-io** [comment]
I think this is normal behavior, 2FA doesn't show the same codes even if the time is correct. 

But since they don't work, your system time is probably out of sync

**Comment by evie-lau** [comment]
I ran into this problem too, and resyncing the time on my PC fixed it.

**Comment by Hweord** [comment]
I have same problem. +1

**Comment by muktadir921** [comment]
Problem solved . pc and mobile need to be same time and date
