### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Barracuda1337** [ente-io/ente#2356]
### Description

Hello. I downloaded the latest version of the ente application and tried to log in, but I cannot log in.

[ente-logs-2024-Jul-3-14-1.zip](https://github.com/user-attachments/files/16086012/ente-logs-2024-Jul-3-14-1.zip)

### Version

3.0.17

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Related https://github.com/ente-io/ente/issues/2178
