### ISSUE TITLE
App Closing issue when i right-click on the auth code on Android!

### ISSUE THREAD

**Issue by NeeL21YT** [ente-io/ente#2402]
### Description

So, i was testing that if that auth edit menu opens on mobile too using right-click using a otg and a mouse, but when i do that the app minimises. Please fix this bug and add that auth edit feature in Android App too! 

### Version

3.0.12

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
On mobile app, please swipe left for editing codes.
