### ISSUE TITLE
Passkeys does not support Yubikey NFC on iOS

### ISSUE THREAD

**Issue by sv3nnie** [ente-io/ente#2406]
### Description

When trying to log in or set up a Yubikey using NFC on ente, the security key is not recognized. A popup from the Yubikey authentication app appears, confirming that the security key is detected, but there is no response from ente. Typically, ente should recognize the key and either add it to my account or log me in.

I use the security key across several browsers and services, but this issue occurs only with ente.

https://github.com/ente-io/ente/assets/67653224/badc39aa-553a-43f8-be6d-22e6cf1b4c5f

### What product are you using?

Ente Photos, Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by mnvr** [comment]
This should be fixed by https://github.com/ente-io/ente/pull/2431. Can you please try again?

**Comment by sv3nnie** [comment]
Can confirm it's working now. Thanks a lot!
