### ISSUE TITLE
Ente Auth Web App takes forever to load

### ISSUE THREAD

**Issue by a-irsyad** [ente-io/ente#2443]
### Description

https://auth.ente.io/login take forever to load. It only shows loading circle that never ends.

I have tried it on Firefox, Chromium and Brave. All the results are the same.

### Version

Web App

### What product are you using?

Ente Auth

### What platform are you using?

Web - Chrome

**Comment by mnvr** [comment]
This is likely a network specific issue depending on your ISP. For example, this happens (sometimes, not always) for sites hosted on Cloudflare (like auth.ente.io) when the accessed from Airtel - https://broadband.forum/threads/can-somebody-contact-airtel-to-fix-their-cloudflare-peer-issue.221867/

**Comment by a-irsyad** [comment]
So, there's nothing I can do to tackle the issue? Will using VPN changes anything?

**Comment by mnvr** [comment]
VPN might help!

**Comment by a-irsyad** [comment]
> VPN might help!

Yap, I confirm that I can load the login page if I use VPN.
