### ISSUE TITLE
Unable to login, Ente Auth desktop app, Windows 11 Pro

### ISSUE THREAD

**Issue by marklesterb28** [ente-io/ente#2467]
### Description
attached is log file and screenshot of error. 
[2024-7-17.txt](https://github.com/user-attachments/files/16261793/2024-7-17.txt)

` [ente_logging] [INFO] [2024-07-17 06:17:53.947627] log file for today: File: 'C:\Users\markl\AppData\Roaming\Ente Technologies, Inc\Ente Auth/logs/2024-7-17.txt' with prefix 
[ente_logging] [INFO] [2024-07-17 06:17:53.947627] app version: '3.0.17+317'
[ente_logging] [INFO] [2024-07-17 06:17:53.947627] 
 [main] [INFO] [2024-07-17 06:17:53.947627] Starting app in foreground
 [Configuration] [INFO] [2024-07-17 06:17:54.117643] Skipping temp folder clear
 [WindowsHttpClient] [INFO] [2024-07-17 06:17:54.140642] Adding certificate to trusted certificates
 [WindowsHttpClient] [INFO] [2024-07-17 06:17:54.140642] Certificate added to trusted certificates
 [UpdateService] [SEVERE] [2024-07-17 06:17:54.320656] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [INFO] [2024-07-17 06:17:54.320656] Debouncing notification
 [UpdateService] [SEVERE] [2024-07-17 06:17:54.320656] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [_LoginPageState] [SEVERE] [2024-07-17 06:18:03.377360] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 06:18:03.594377] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [_LoginPageState] [SEVERE] [2024-07-17 06:18:11.573503] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 06:18:11.786946] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [_LoginPageState] [SEVERE] [2024-07-17 06:18:18.472193] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 06:18:18.685209] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [_LoginPageState] [SEVERE] [2024-07-17 06:18:36.448063] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 06:18:36.663189] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [_LoginPageState] [SEVERE] [2024-07-17 06:18:44.555311] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 06:18:44.770270] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [ente_logging] [INFO] [2024-07-17 06:22:51.681254] log file for today: File: 'C:\Users\markl\AppData\Roaming\Ente Technologies, Inc\Ente Auth/logs/2024-7-17.txt' with prefix 
[ente_logging] [INFO] [2024-07-17 06:22:51.681254] app version: '3.0.17+317'
[ente_logging] [INFO] [2024-07-17 06:22:51.681254] 
 [main] [INFO] [2024-07-17 06:22:51.681254] Starting app in foreground
 [Configuration] [INFO] [2024-07-17 06:22:51.717255] Cleared temp folder
 [WindowsHttpClient] [INFO] [2024-07-17 06:22:51.744258] Adding certificate to trusted certificates
 [WindowsHttpClient] [INFO] [2024-07-17 06:22:51.745257] Certificate added to trusted certificates
 [UpdateService] [SEVERE] [2024-07-17 06:22:51.920270] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [SEVERE] [2024-07-17 06:22:51.921271] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [INFO] [2024-07-17 06:22:51.921271] Debouncing notification
 [_LoginPageState] [SEVERE] [2024-07-17 06:22:57.995890] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 06:22:58.210904] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [ente_logging] [INFO] [2024-07-17 03:18:13.216127] log file for today: File: 'C:\Users\markl\AppData\Roaming\Ente Technologies, Inc\Ente Auth/logs/2024-7-17.txt' with prefix 
[ente_logging] [INFO] [2024-07-17 03:18:13.216127] app version: '3.0.18+318'
[ente_logging] [INFO] [2024-07-17 03:18:13.216127] 
 [main] [INFO] [2024-07-17 03:18:13.216127] Starting app in foreground
 [Configuration] [INFO] [2024-07-17 03:18:14.526504] Skipping temp folder clear
 [UpdateService] [SEVERE] [2024-07-17 03:18:14.754318] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [SEVERE] [2024-07-17 03:18:14.754318] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [INFO] [2024-07-17 03:18:14.754318] Debouncing notification
 [_LoginPageState] [SEVERE] [2024-07-17 03:18:32.341700] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-17 03:18:32.561718] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
`

![Screenshot 2024-07-17 031852](https://github.com/user-attachments/assets/2e99c6a4-7bb7-4f96-9363-6ec817d01a61)

I am using the latest beta version auth-v3.0.18-beta.1

please let me know what else I can do to help troubleshoot / fix the issue. thank you!

### Version

auth-v3.0.18-beta.1

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Related https://github.com/ente-io/ente/issues/2178
