### ISSUE TITLE
Unlocking Touch ID on iPad

### ISSUE THREAD

**Issue by spotter226** [ente-io/ente#2509]
### Description

When you open the Auth app on iPad with Touch ID, you have to click on "unlock me" in the center of the screen before entering your fingerprint. I suggest eliminating this option because it is inconvenient.

### Version

3.0.12

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by benmneb** [comment]
if touch id is enabled ("lockscreen" option in security settings) when the app is opened it should automatically ask for biometric authentication with having to take any further action.

theres no other action to take other than press the button anyway, obviously that's what we're there for.

thanks for the great app 🙏

**Comment by spotter226** [comment]
As you can see from the video when I open the app it doesn't automatically ask me to enter Touch ID

https://github.com/user-attachments/assets/cdabfa42-900a-4fa4-801a-0d9eff68feb6

**Comment by benmneb** [comment]
i see this screen changed design in the latest update 👀 and an icon to logout was added, and you can now tap anywhere else on the screen to prompt for biometic auth... but for a smoother UX it should prompt for biometric authentication (if already allowed in settings of course) immediately upon launch without having to tap anywhere. then if someone doesn't want to, they can just press the logout button. obviously i haven't seen your analytics, but i would imagine almost everyone who opens the app logs in, so this should be the default route with least steps to success.

**Comment by spotter226** [comment]
Here's the log for you. I hope you can find a solution.
[ente-logs-2024-Aug-25-14-39.zip](https://github.com/user-attachments/files/16740719/ente-logs-2024-Aug-25-14-39.zip)

**Comment by ashilkn** [comment]
>>> but for a smoother UX it should prompt for biometric authentication (if already allowed in settings of course) immediately upon launch without having to tap anywhere.

This is the current behaviour. Haven't been able to reproduce it yet. 
@AmanRajSinghMourya You might want to take a look at this.

**Comment by benmneb** [comment]
Now is probably a good time to mention I’m using the iPad app on latest macOS

**Comment by benmneb** [comment]
4.0.x seems to have fixed this 🥇 

i think its safe to close this issue now

thanks again
