### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by LaoJiuYes** [ente-io/ente#2561]
### Description
Hi everyone, seeking help on what this is and how to fix it. Thank you!
Error reported during yarn build:
=> [web ente-builder 6/6] RUN yarn build                                                                                                      28.4s
 => => # $ /app/node_modules/.bin/next build                                                                                                        
 => => #   ▲ Next.js 14.2.4                                                                                                                         
 => => #   - Environments: .env                                                                                                                     
 => => #    Linting and checking validity of types ...                                                                                              
 => => #  ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-c
 => => # onfig

### Version

Publishing a version of this help wanted post

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by mnvr** [comment]
Do you mean "The Next.js plugin was not detected in your ESLint configuration."? This is a harmless warning, you can ignore it.

**Comment by mnvr** [comment]
Your `node` process is running out of memory (`yarn build` calls `next build` which internally uses `node`). I can't say much why that is happening. Perhaps there might be some related issue in the Next.js discussions. 

The only suggestion that comes to my mind is to try doing the `yarn build` on a system with more RAM.
