### ISSUE TITLE
Proton Mail "Not a valid email"

### ISSUE THREAD

**Issue by MillerApps** [ente-io/ente#2599]
## Bug/Lack of Feature:
-  It would seem that ProtonMail addresses are not supported.
-  Both the base Proton address and one using an alias (i.e., username+ente@proton.me)
## Hope:
-  I would hope to see this supported in the near future.

### Version

3.0.17

### What product are you using?

Ente Photos, Ente Auth

### What platform are you using?

Mobile - iOS, Desktop - macOS, Web - Chrome

**Comment by brog-io** [comment]
Hm, this is odd. I'm using Proton Mail and it works fine. Are you sure you didn't make a typo or already registered with that email? Many people using Ente also use Proton, so they definitely didn't block them.

**Comment by Krystian95** [comment]
Hi, I was able to Signup and Login into Ente Auth apps (iOS and macOS) with my Proton email (@proton.me).

**Comment by MillerApps** [comment]
> Hm, this is odd. I'm using Proton Mail and it works fine. Are you sure you didn't make a typo or already registered with that email? Many people using Ente also use Proton, so they definitely didn't block them.

As it turns out, when I created my email, I actually made a typo and was missing a letter. A very dumb mistake on my part. Sorry for the false report.
