### ISSUE TITLE
Ente-Auth Black Screen on Arch Linux

### ISSUE THREAD

**Issue by JunaidQrysh** [ente-io/ente#2602]
### Description

I have installed all three packages of ente-auth on Arch Linux, they all show black screen on startup and nothing happens.
I am using hyprland(a wayland window manager).

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by JunaidQrysh** [comment]
Stupid of me, I did not install gnome-keyring.

**Comment by adursh** [comment]
I already have gnome-keyring set, still I get the black screen issue. How did you solve it?
