### ISSUE TITLE
Ente Auth Web 2FA Codes appear too late compared to Ente Auth Mobile App

### ISSUE THREAD

**Issue by gitLudovic** [ente-io/ente#2657]
### Description

When trying to authenticate on any app using the 2FA codes provided by the web version of Ente Auth, all of them will fail.

I noticed that this was due to the valid codes appearing later than their validity when checking on the Mobile App (which works). 

When the valid code appeared on the Mobile App, it would only appear two codes later on the Web App, leading to my assumption that the codes appearing in the Web App were late, and would therefore expire before I could even see them.

I cannot however show any demonstration, as the Mobile App does not allow for screen sharing or capture of any sort.

### What product are you using?

Ente Auth

### What platform are you using?

Web - Firefox

**Comment by mnvr** [comment]
The time in your browser might be incorrect. You mentioned Firefox, there have been other users who have reported that Firefox provides incorrect time when various privacy settings are enabled.

(The codes depend on time. If the time is the same on both browser and mobile, the codes you see will be the same)

**Comment by gitLudovic** [comment]
I see,

After testing on a fresh install of firefox, it does in fact show the right codes.

Thank you.
