### ISSUE TITLE
[auth][windows] Auth uses GPU when window is hidden in tray

### ISSUE THREAD

**Issue by brandon14** [ente-io/ente#2686]
### Description

I noticed that using the latest 3.1.1 Auth on Windows 11, the auth process will still consume around 8%-15% of GPU usage even if you hide the window in the system tray.

This may not be the intended behavior and maybe how the window is hiding in the system notification tray. Most other applications consume little to no GPU when they are not in focus or otherwise minimized to the taskbar or system tray. It seems that Auth is using this amount of GPU regardless of whether the window is visible.

OS: Windows 11 23H2
Auth: v3.1.1

To replicate this behavior on Windows, launch Auth, right-click on the system notification tray icon, and click hide window. You will notice in the task manager that the Auth process is still consuming GPU even though the window is minimized to the notification tray.

If you need any additional information just let me know and I will be happy to provide whatever I can.

![image](https://github.com/user-attachments/assets/a88c4167-67c8-4f3f-a054-10b18a477791)

### Version

3.1.1

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by brandon14** [comment]
I would like to update this and say that on the latest 4.0.0 version, the GPU usage is down to around 1.0%-2.0%.

**Comment by aith85** [comment]
Same on W10 22H2 19045.5198.
Ente v1.4.5 and previous one.
Constant 25-30% cpu usage and also GPU when open.

![image](https://github.com/user-attachments/assets/5a1c3111-ddf0-43fb-bcd2-290c217d6fc5)
