### ISSUE TITLE
The recovery key doesn't work

### ISSUE THREAD

**Issue by 1LuisVargas** [ente-io/ente#2733]
### Description

I've tried copy-pasting the recovery key on Android and on PC, and the recovery key just doesn't work, which is very concerning, because it makes the entire point of getting and storing a recovery key pointless.

Every time I get "Incorrect recovery key", "The recovery key you entered is incorrect : recovery code should have 24 words". Again, I am copy-pasting, so no room for human error here.

### Version

3.1.1

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows

**Comment by ua741** [comment]
Hey @1LuisVargas,

Can you please write to support[at]ente.io? As the error message says, the recovery key needs to be 24 words, but looks like that is not the case. Also, please confirm using which device you signed up.

**Comment by 1LuisVargas** [comment]
Sure, I'll write a ticket then.

I signed up using my Samsung Galaxy A55.

**Comment by 1LuisVargas** [comment]
After updating to beta version 3.1.2 it is now working properly. Thanks for the help on the support ticket Neeraj.
