### ISSUE TITLE
A Javascript error occured in the main process

### ISSUE THREAD

**Issue by AmanDevelops** [ente-io/ente#2747]
### Description

I downloaded the file from official ente.io
when i launch the application, i get the error
![Screenshot (4)](https://github.com/user-attachments/assets/0707f3bb-1066-4ab3-b59f-a93053099be8)

sha256 - 594A5C0C79F492B57B22779F8E2C9886EB87C57DA645CDD50408CAA85B5150EA

### Version

1.7.2

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
https://help.ente.io/photos/troubleshooting/desktop-install/#windows
