### ISSUE TITLE
[web][photos] String not translated

### ISSUE THREAD

**Issue by dnred** [ente-io/ente#2753]
### Description

English - "X memories"
Polish - "X memories"

The string isn't translated to Polish at least. It is on the main Photos page.

### Version

Latest as of 19.08.2024

### What product are you using?

Ente Photos

### What platform are you using?

Web - Brave

**Comment by mnvr** [comment]
Thank you for catching this. This looks like an issue (or atleast, an unexpected behaviour) in the way our localization library treats plurals in Polish.

I've fixed it with https://github.com/ente-io/ente/pull/2759 - You should be seeing the correct translation now.
