### ISSUE TITLE
Ente Auth Folders should not be in the Home directory on Linux

### ISSUE THREAD

**Issue by shahiljain** [ente-io/ente#2775]
### Description

Ente Auth creates two folders `ente` and `temp` in the home folder of Linux. These folders clutter the home directory which is basically the homepage for linux users. 

Moreover the `temp` folder does not indicate that it was created by ente-auth so it is confusing to a user why it is there if they don't immediately spot it after installing ente-auth. This can cause user frustration as they keep deleting the folder and it keeps re-appearing.

There are three solutions I can propose.

1. Move the folders to ~/.config/ente
2. Move the folders to ~/.local/share/ente_auth
3. On the home folder itself move the folders to .ente folder (This way they stay hidden)

These are the most common practices for linux apps. I think the third option is the easiest to implement.

### Version

3.1.1.

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by MithicSpirit** [comment]
This seems related to #2564. Note that the third solution, although easiest, would not conform to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/).

**Comment by prateekmedia** [comment]
Continuing the discussion here https://github.com/ente-io/ente/issues/2564

**Comment by prateekmedia** [comment]
Continuing it here, seems like I am unable to replicate this issue. Are you sure you have all the xdg directories environment variables correctly set? Also you referred ~/temp directory, could you tell me the content that ente auth creates inside it. Is it logs?

**Comment by prateekmedia** [comment]
Please reply the above answer in this issue: #2563
