### ISSUE TITLE
Windows on Arm

### ISSUE THREAD

**Issue by TNT44777** [ente-io/ente#2818]
### Description

Hello,

I tried to download ente auth on a win on arm device the installer just doesnt work but the zip shows the login screen but when i go to sign in it gives me an error. See log file below

[ente-logs-2024-Aug-22-8-12.zip](https://github.com/user-attachments/files/16707570/ente-logs-2024-Aug-22-8-12.zip)

K.r. TNT

### Version

V3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by prateekmedia** [comment]
None of the team members use windows on arm so we can't say much. But still you can following this guide to see if it fixes your issue:
https://github.com/ente-io/ente/discussions/2819

**Comment by TNT44777** [comment]
Hello thanks that fixed it
