### ISSUE TITLE
[Auth][Bug] Unable to import from 2FAS Auth when backup includes Steam tokens

### ISSUE THREAD

**Issue by dimaguy** [ente-io/ente#2830]
I'm running Ente Auth 3.1.1 and when I try to import my 2FAS backup (encrypted or cleartext) it doesn't recognize the Steam tokenType(with a very obscure error by the way "Unable to recognize OTP type").
I confirmed it was an issue with the Steam tokens the moment I removed that specific one from the backup and the import finally went through.

**Comment by ua741** [comment]
Thanks for reporting. Fix for this issue will go out in the next release.
