### ISSUE TITLE
Unable to add mozilla to ente auth

### ISSUE THREAD

**Issue by 3nderall** [ente-io/ente#2846]
### Description

When adding my mozilla account to the list of codes in the ente auth app the code generated would not be accepted by the setup page for 2fa. I have tried the qr code and manually putting the key in.

### Version

v3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Can you verify that your system time is correct? You can open https://time.is/ on your device to validate this.

**Comment by 3nderall** [comment]
> Can you verify that your system time is correct? You can open https://time.is/ on your device to validate this.

Time is exact on the device with the app and 37.4 seconds behind on the device where I was managing my mozilla acount

**Comment by 3nderall** [comment]
I synced the time with the device making the qr code/secret key and it worked a couple hours later
