### ISSUE TITLE
Aegis import fail

### ISSUE THREAD

**Issue by mrx23dot** [ente-io/ente#2870]
### Description

Tried to import TOTP json from Aegis,
**both** plain and encrypted failed with error message:

`error type Null is not a subtype of type Iterable<dynamic>`

No crashing like in 
https://github.com/ente-io/ente/issues/1934

using Aegis 2.0.3

### Version

3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Hey @mrx23dot,
Can you please the the logs here. (Settings -> Support -> Report a bug) will show an option to export the logs.
Also, please confirm which version of Aegis you are using for exporting.

**Comment by ua741** [comment]
Thanks for the log. This will be fixed in the upcoming release.
If you want to import before that, can you please edit any code in Aegis and add it to a group. Once that's done, you should be able to export the code from Aegis, and import them to Ente Auth.
