### ISSUE TITLE
Not working weblink on ente/blob/main/desktop/docs/dependencies.md

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2884]
### Description

1. Open [https://github.com/ente-io/ente/blob/main/desktop/docs/dependencies.md](https://github.com/ente-io/ente/blob/main/desktop/docs/dependencies.md)

2. Click on  "bundle a static export of the [Photos web app](https://github.com/ente-io/ente/blob/main/desktop/web/README.md) in the generated app."
3. 
![image](https://github.com/user-attachments/assets/d486888c-16dc-4d54-8385-663f42cfd14d)

![image](https://github.com/user-attachments/assets/fc4c2f73-b9b0-4961-a50c-8645e715c4f6)

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
Fixed. Thank you!
