### ISSUE TITLE
Not working weblinks on ente/blob/main/docs/docs/auth/migration-guides/index.md

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2886]
### Description

1.Open [https://github.com/ente-io/ente/blob/main/docs/docs/auth/migration-guides/index.md](https://github.com/ente-io/ente/blob/main/docs/docs/auth/migration-guides/index.md)

![image](https://github.com/user-attachments/assets/1cbe9914-578c-4556-a505-127818ca83a7)

2. Click on last two weblinks. **NOT WORKING**

![image](https://github.com/user-attachments/assets/59645c2f-e947-4d48-a3ec-fbf8f3f7c8c9)

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by Tuscann** [comment]
![image](https://github.com/user-attachments/assets/3931d450-9795-401b-97f0-ea161483a52d)
Is The problem here is diferent tree structure @sv3nnie ?

**Comment by sv3nnie** [comment]
Those links also work fine for me on the help site: https://help.ente.io/auth/migration-guides/#migrating-to-from-ente-auth

**Comment by Tuscann** [comment]
Why  /authy/index.md and /steam/index.md are put in sub folders?

**Comment by ua741** [comment]
Help docs are supposed to be opened from https://help.ente.io/auth/migration-guides/ and the above links works fine if you access via that website.
