### ISSUE TITLE
Not working links on ente/docs/docs/de/auth /index.md

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2887]
### Description

1. Open [https://github.com/ente-io/ente/blob/main/docs/docs/de/auth/index.md](https://github.com/ente-io/ente/blob/main/docs/docs/de/auth/index.md)

2. Click on weblink

![image](https://github.com/user-attachments/assets/1b85f361-061a-429b-8442-91adc4873942)

**Comment by Tuscann** [comment]
Where this code is used in the website [sv3nnie](https://github.com/sv3nnie)  ?

**Comment by sv3nnie** [comment]
@Tuscann It's used on https://help.ente.io/de/auth/#ente-auth

**Comment by Tuscann** [comment]
@sv3nnie  Do you see **de** in the url [https://github.com/ente-io/ente/blob/main/docs/docs/de/auth/index.md](https://github.com/ente-io/ente/blob/main/docs/docs/de/auth/index.md)

de?

**Comment by Tuscann** [comment]
Not a bug in this case.
