### ISSUE TITLE
Not working weblink on ente/docs/docs/photos/faq /export.md

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2888]
### Description

1.  Open [https://github.com/ente-io/ente/blob/main/docs/docs/photos/faq/export.md](https://github.com/ente-io/ente/blob/main/docs/docs/photos/faq/export.md)

2. Click on **migration/export** weblink
3. Now working

![image](https://github.com/user-attachments/assets/967c791a-db6d-4103-bc81-1d80beee926a)

**Comment by sv3nnie** [comment]
The migration/export link works fine for me on the help site: https://help.ente.io/photos/faq/export#can-i-backup-my-data-in-a-local-drive-outside-ente

**Comment by Tuscann** [comment]
Not a bug in this case.
