### ISSUE TITLE
[Website] Not working weblink on https://ente.io/blog/collaborative-albums

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2890]
### Description

1. Open [https://ente.io/blog/collaborative-albums](https://ente.io/blog/collaborative-albums)
2. Click on weblink text **album collaboration.**

![image](https://github.com/user-attachments/assets/26e09cc5-985f-40bf-8948-58f34da106b2)

![image](https://github.com/user-attachments/assets/5c675348-5907-47f6-b9d2-42c85c4888d2)

### What platform are you using?

Web - Firefox

**Comment by vishnukvmd** [comment]
It'll not be possible to keep a track of broken links to fix where a third party service has gone away.

**Comment by Tuscann** [comment]
Easy solution @vishnukvmd :  Remove broken link from your website.
