### ISSUE TITLE
[Docs][Website] Clarification for information https://github.com/ente-io/ente/blob/main/docs/docs/photos/faq/subscription.md

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2891]
### Description

1. Open [https://github.com/ente-io/ente/blob/main/docs/docs/photos/faq/subscription.md](https://github.com/ente-io/ente/blob/main/docs/docs/photos/faq/subscription.md)

2. Check text:

What happens when my subscription expires?
30 days after your subscription expires, **all of your uploaded data** will be cleared from our servers.

Add that first free 5GB are stay on server that mean not **all of your uploaded data** is deleted.

![image](https://github.com/user-attachments/assets/19fc9615-5840-42e2-bff6-c9dfdccc72ff)

**Comment by vishnukvmd** [comment]
The documentation is correct.
