### ISSUE TITLE
Editing Photos loses megapixels / resolution

### ISSUE THREAD

**Issue by cpaulik** [ente-io/ente#2894]
### Description

When I edit a photo, either a small crop or just light or color. 
The photo saved is much lower resolution than the original.

e.g. I have a 24MP photo 4000x6000 pixels. I press edit adjust the `Light` slider and save a copy. The copy is 1920x2880 in my case.

### Version

v0.9.27

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by AntsyBoi** [comment]
Also having this issue, photos I rotate within the app go from 3072x4080 to 1920x1445 even though I didn't crop or do any other edits other than pressing the rotate button.

**Comment by AntsyBoi** [comment]
Bump

I would love to see this get patched as it sucks losing lots of resolution just cause you wanted to slightly tweak a photo.
