### ISSUE TITLE
Different texts and icons for play album on TV in the app and documentation

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2896]
### Description

1. Open h[ttps://help.ente.io/photos/features/cast/](https://help.ente.io/photos/features/cast/)
2. Open album in desktop app and click Play album on TV

**Check different text on documentation not same like in app?** 

![image](https://github.com/user-attachments/assets/72407791-ed4b-42ae-a2e2-40fc56c0f7a7)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by ua741** [comment]
This is intended difference. The web downloads the chrome sdk from google service, while mobile uses different protocol.
