### ISSUE TITLE
Typo on https://help.ente.io/photos/features/collaborate#collaborative-links

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2898]
### Description

1. Open [https://help.ente.io/photos/features/collaborate#collaborative-links](https://help.ente.io/photos/features/collaborate#collaborative-links)

2. Check text When a collaborator is removed from a shared album (or when they leave the album), any photos they**'d** uploaded will also be removed.

What is 'd ? I think this is typo.
![image](https://github.com/user-attachments/assets/e3bc2aea-7723-47b0-ad04-fdc5228982bc)

![image](https://github.com/user-attachments/assets/e3bc2aea-7723-47b0-ad04-fdc5228982bc)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by ua741** [comment]
> What is 'd ? I think this is typo.

any photos they had uploaded
