### ISSUE TITLE
Missing fav icon

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2904]
### Description

1.  Open [](https://ente.io/assets/screenshots/light/04-family-plans-screen.png)
2.  Check fav icon

**Missing favicon**

![image](https://github.com/user-attachments/assets/6048c4e2-1700-408d-9b12-1dae7fc09192)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by vishnukvmd** [comment]
You're looking for a favicon after opening a photo. This is a browser specific implementation, unrelated to us.
