### ISSUE TITLE
[Website] Not working weblinks on https://ente.io/privacy

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2905]
### Description

1. Open [https://ente.io/privacy](https://ente.io/privacy)
2. Check link **Privacy Policy: https://www.scaleway.com/en/privacy-policy/**
![image](https://github.com/user-attachments/assets/085c4cde-2cdf-4867-a92d-003ed273f6e6)

![image](https://github.com/user-attachments/assets/b82a69ed-7754-4c6b-ba1b-50a75a5e5fbc)

3. Check link under text 
Privacy Policy: https://www.featuremonkey.com/privacy/

![image](https://github.com/user-attachments/assets/f17b5d7b-e912-4501-a66b-aa32745828cb)

![image](https://github.com/user-attachments/assets/396960bd-2370-4aaf-8f46-c1b7912a5035)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by vishnukvmd** [comment]
Barring Scaleway, the rest of the links are working. I've written to their team about this.
