### ISSUE TITLE
[Desktop][Ente] Missing green tick when option Sync continuously is on 

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2919]
### Description

1. Open Ente Desktop on Windows
2. Click on Dots
3. Click on Export Data
4. Click on Sync Continuosly.Try to be on
5. Check color of slider

Why is not green ?

![22](https://github.com/user-attachments/assets/aec67566-f0cc-473d-bae1-fa5a2f051690)

![image](https://github.com/user-attachments/assets/368612b3-de62-4c25-9b5e-42d3d3608d34)

 

### Version

1.7.2

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
You are running a very old version of the code locally. This problem does not exist in the production release.

**Comment by Tuscann** [comment]
This is production release @mnvr.
I do know not how to run your system locally.
