### ISSUE TITLE
Ripple effect on button Upload

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2921]
### Description

1. Open desktop app
2. Click button Upoad
3. Click add Folder
4. Click add File
5. Click Google takeout
6. Click x
7. Check state of button Upload

Broken position
![image](https://github.com/user-attachments/assets/e82e7151-452a-494b-a47a-dbe4a471b75e)

Normal position
![image](https://github.com/user-attachments/assets/9cf9945b-6f01-4a4f-9bed-fa8c07343961)

### Version

1.7.3

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
You need to stop opening these issues. You've opened tens of issues since yesterday night, and at this point it is coming off as spam. I assume you're trying to help, but whatever you're doing is not helping.

**Comment by Tuscann** [comment]
You have plenty of small problems to fix ! @mnvr

**Comment by mnvr** [comment]
Again, I'm assuming good intent, and that you're genuinely trying to help. I'm trying to tell you opening issues about various nits is not helping. 

e.g. the "strange look" you see here is a ripple effect provided by MUI, the library we use for our UI components. I also don't like the ripple effect, but before disabling it we need to ensure we give some other indication of the hover state. This is something I've discussed and planned, and we'll do over the longer term, but opening an issue about each hover button state is not being useful. Or opening issues about grammar ("they'd" is correct, btw). Or folder organization.

**Comment by Tuscann** [comment]
You are write for they'd. 
1. Can you write with more simple words with full version **they had** not short version they'd.
@mnvr 
2. I am only giving my opinion for UI. I have only one ticket for hover button. I do not known your plans for ripple effect provided by MUI, the library we use for our UI components
3. For folder organization my bugs are small fixes.

**Comment by vishnukvmd** [comment]
Closing, since we do not intend to fix the behavior of these buttons right now.
