### ISSUE TITLE
[Browser][EntePhoto] Not working link on support on computer without default mail app

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2926]
### Description

1. Open https://web.ente.io/gallery in Firefox
2. Click 3 lines
3. Click Support
4. Open empty window

![image](https://github.com/user-attachments/assets/e83f902c-10a3-4eed-92b6-8e2adb5248c6)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Firefox

**Comment by ua741** [comment]
Clicking on support opens default mail app. You might not have a email client configured, which is why you are seeing empty window `mailto:support@ente.io`

**Comment by Tuscann** [comment]
@ua741 You are right I do not have default mail app because this is old Windows 7 laptop.

**Comment by Tuscann** [comment]
@ua741 You are right I do not have default mail app because this is old Windows 7 laptop.
