### ISSUE TITLE
[Auth][Mobile] Old pictures in iOS App Store for Ente Auth

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2942]
### Description

1. Open https://apps.apple.com/in/app/ente-auth/id6444121398?platform=iphone
2. Check uploated pictures to Ente Auth

Different name Ente Auth vs ente Aunteticator ?
Missing to show new feature icon for search ?
Missing to show new feature icon tags ?

**Update photos in App Store with new one.**

![44444](https://github.com/user-attachments/assets/90aa0fef-0ffe-4f88-8a50-e8c1526c39f4)

![image](https://github.com/user-attachments/assets/f028333b-c4ed-4945-82f4-7cdb0c2153d8)

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by vishnukvmd** [comment]
This is a known issue, we'll look into this later.
