### ISSUE TITLE
[Web][Photos] Put coma to end of sentence on https://web.ente.io/deduplicate

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2943]
### Description

1. Open desktop
2. Create one album add 2 photos
3. Create second album add same to photos
4. Delete all 4 photos
5. Click on 3 lines
6. Click on Deduplicate files
7. Check text : "The following files were clubbed based on their sizes, please review and delete items you believe are duplicates"

Missing dot on end of sentence.

![image](https://github.com/user-attachments/assets/39e79ef2-1d1a-4c32-9de5-ef221ea9b416)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by vishnukvmd** [comment]
There are a lot more strings where we aren't closing them with a period. Please do not open fresh issues for each of them. We will take a look at these in bulk later.
