### ISSUE TITLE
[Photos] [Desktop] Error when try to toggle off Machine learning

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2944]
### Description

1. Open  [https://web.ente.io/gallery](https://web.ente.io/gallery)
2. Click 3 lines
3. Click Preferences
4. Click Machine learning
5. Toggle to on 
6. Try to toggle off throw error

[error] Failed to disable ML: Error: Attempting to assert globalThis.electron in a non-electron context 

![image](https://github.com/user-attachments/assets/738ac7c9-81ff-47e9-b2f2-4249dea606f1)

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by mnvr** [comment]
You are running a development server for your desktop app. The web app is connecting there. This is not a real problem.

**Comment by Tuscann** [comment]
@mnvr From where coming this error ? I am using web version of https://web.ente.io/gallery on Debian mashine.
