### ISSUE TITLE
Maybe wrong size of window of Pending Items when stop export data manually

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#2963]
### Description

1. Open Ente Photos on desktop app
2. Check size of window of left items
3. Only can see small thumbnail and part of the name of picture
4. **Is this normal size of this window?** Do you have figma screen for that?
  
![image](https://github.com/user-attachments/assets/2b592536-f10f-49d1-960a-163cf3d45662)

### Version

1.7.3

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by vishnukvmd** [comment]
Your intent might be to make Ente better, but you are mindlessly opening too many issues and causing distress. This is not the right way to contribute to any opensource project.

Do not open any more issues, or you will be banned.
