### ISSUE TITLE
Error when trying to login in the dektop client of Ente Auth

### ISSUE THREAD

**Issue by tusharsagar10900k** [ente-io/ente#3007]
EDIT: My desktop app now works. I didn't change anything, just decided to give it another go after about 24 hours. Though I would like to keep this thread open, as I believe many people still are facing this issue.

### Description

When I enter my email and click on "Log In" it gives an error and says "It looks like something went wrong. Please retry after some time, if the error persists, please contact our support team." I tried the latest v3.1.3 as well as the 3rd latest v3.1.0 but neither of them worked. The Ente Photos app is working though. I am using Windows 11 Pro

Things I noticed:

1) I tried to run Ente Auth on Windows Sandbox, and it actually worked there (I had to install Microsoft Visual C++ 2015 - 2022 Redistributable, otherwise I was getting missing dll errors, but after installing that it worked just fine). I managed to log in without any real issues on the Sandbox. But it isn't working on my actual real windows 11 PC.

2) This error appeared regardless of whether the email id used is registered for Ente account, not registered for an Ente account, or heck this error comes up even when I put a gibberish fake email id.

3) Someone posted this same issue [last week](https://github.com/ente-io/ente/issues/2751). They said the problem was Windows 11, but since I was able to login in windows 11 sandbox, I don't think that's the issue unless I am missing something (I believe that actual windows 11 and sandbox windows 11 isn't exact same, so that might have affected my result, I don't have access to any other real windows 11 machine.)

4) I can't make a new account from the desktop client either.

In an attempt to fix this issue, I tried disabling Windows Defender's real time protection, Smart Screen, PUP blocking and even Core Isolation but nothing worked. I also tried reinstalling Visual C++ Redistributable but that didn't work either. Tried updating windows which didn't work either. Lastly I tried installing the oldest version I could find, v3.0.1 which didn't work either, so I reinstalled v3.1.3 which again didn't work.

Here is the latest log file:
[2024-8-28.txt](https://github.com/user-attachments/files/16769963/2024-8-28.txt)

Apologies if I missed something relevant or included something irrelevant, it's my first time posting here on GitHub. Also apologies if this issue is already known and is being worked on or already fixed and is scheduled to release in a future update.

### Version

v3.1.3, v3.1.0, v3.0.1

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by kabilan-dt** [comment]
Same issue is happening for me. Working fine in Mac OS client. Unable to use windows client. 
Windows OS 11. 23H2 with latest august update

**Comment by thekurst** [comment]
Same issue here as well and I'm on Windows 10 22H2 (19045.4780) running the latest version of the ente auth client 3.1.3.

Relevant error from logs:

`Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [SEVERE] [2024-08-29 14:31:57.651450] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UpdateService] [INFO] [2024-08-29 14:31:57.651450] Debouncing notification
 [_LoginPageState] [SEVERE] [2024-08-29 14:32:04.903450] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-08-29 14:32:05.136341] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))`

**Comment by ua741** [comment]
Can you please try to update your trusted root certificates on your machine, and comment here if that resolves the issue.
https://help.ente.io/auth/troubleshooting/windows-login
cc @prateekmedia

**Comment by thekurst** [comment]
That worked, thanks!
