### ISSUE TITLE
Looks prices of Apple apps strore

### ISSUE THREAD

**Issue by Tuscann** [ente-io/ente#3016]
### Description

1. Open on Iphone 15 Apple App store for Ente photos
2. Check prices

**Why 200 GB(1 Month) - 12.99 лв. is show twice ?**
Why 50 GB(1 Month) - 6.99 лв. is show twice ?

![image](https://github.com/user-attachments/assets/23f53a8a-dd7d-4819-8210-979e336ef3c2)

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - iOS

**Comment by ua741** [comment]
This could have been an question instead of issue. Please be mindful while creating issues as all team members are sent alert for same.
We had to update our priceIDs and there are customer on older plans.
