### ISSUE TITLE
Improve UX to clearly indicate how to preserve existing albums during Google Takeout import

### ISSUE THREAD

**Issue by andrewbanchich** [ente-io/ente#3067]
### Description

Not sure if this is intended behavior (feature request) or a bug.

I downloaded my Google Photos archive as ZIPs, extracted them to a folder, then clicked Upload -> Google Takeout. The next screen "Upload to album" wants me to choose a new album, existing album, or "Uncategorized".

Looking in the expanded ZIPs, they are already organized into my existing Google Photos albums. Shouldn't Ente just use those? Why would it make me choose one album for an export containing many albums?

### Version

1.7.3

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Linux

**Comment by mnvr** [comment]
https://help.ente.io/photos/migration/from-google-photos/

<img width="745" alt="Screenshot 2024-08-31 at 07 10 18" src="https://github.com/user-attachments/assets/44484dc1-6022-48a4-9bf9-4f8ec70d3db1">

https://help.ente.io/photos/features/albums#uploading-a-nested-folder

**Comment by mnvr** [comment]
I've updated the title of the button now from "New album" to "Create albums" to make it more obvious that clicking on it might do what the user expects (In the future we'll also try to enhance the overall flow if possible to make it even more obvious).

The change is in https://github.com/ente-io/ente/pull/3076, and will be part of the next release.

**Comment by mnvr** [comment]
Forgot to mention - meanwhile, you can just click on the "New album" button after dragging and dropping your takeout, and it will provide you the option to preserve your albums.

**Comment by andrewbanchich** [comment]
Ah, okay. Just some feedback - IMO it would be clearer if the workflow were:

1. select Google Takeout
2. there are three radio buttons, the default selection being "preserve albums", but there are also "create album" and "upload to existing album"

>you can just click on the "New album" button after dragging and dropping your takeout, and it will provide you the option to preserve your albums.

This wouldn't be intuitive for me since I'd think "new album" would only be for creating new albums.

Also, not sure if it does this already, but it would be nice to surface in the UI was the behavior of "preserve albums" is if there's already an album with the same name. I assume it merges the photos within them? Maybe users wouldn't want this and would instead prefer to create "Existing Album (2)"? Or vice versa?

**Comment by mnvr** [comment]
> This wouldn't be intuitive for me since I'd think "new album" would only be for creating new albums.

Sorry, I wasn't clear. We've renamed "New album" to "Create albums". For the build you have, you'll still need to select "New album", but going forward the button will be called "Create albums".


<img width="405" alt="Screenshot 2024-08-31 at 19 54 33" src="https://github.com/user-attachments/assets/1c389411-9cba-4887-913e-6d35deb2d5b0">

(Might not completely solve the issue, but should be at least clearer than the current UX)

**Comment by andrewbanchich** [comment]
Yeah, I agree that is better than the current build! Just mentioning that, in my opinion, it's still not ideal because, personally, I interpret "create albums" to mean "manually create albums" (not what I want for uploading Google Takeout). I'd normally expect an "Upload Google Takeout" workflow to just upload what's there since I'd assume almost everyone will be preserving the existing albums from the export.

If don't understand "Create albums" is what I want, I'm not going to click it, so I won't be taken to the page that explains that it is what I want.

Just adding some feedback for

>In the future we'll also try to enhance the overall flow if possible to make it even more obvious

Thanks!
