### ISSUE TITLE
[web][photos] Cannot view photos made on iOS 18

### ISSUE THREAD

**Issue by saibotk** [ente-io/ente#3186]
### Description

When trying to view images taken on an iPhone with the latest public beta of iOS 18, I experience two issues.
Note, I can verify this only happens since switching to the latest OS version. All images taken before work as normal.

It seems like the image format may have some new attributes or metadata?

I don't really know under what condition which one of them occurs.
Currently, I do not have the time to investigate if I can supply some example images without personal metadata, but I hope this initial report still helps us in finding the root cause :)

## First error - Shows broken image icon in the center

Console logs:
```
Could not parse HEIF file Invalid input: Unspecified: Metadata not correctly assigned to image
[error] Failed to get renderable blob for IMG_4535.HEIC, will fallback to the original: Error: HEIF image not found
Media resource blob:https://web.ente.io/[REDACTED] could not be decoded. [gallery](https://web.ente.io/gallery#&opened)
Media resource blob:https://web.ente.io/[REDACTED] could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006) [gallery](https://web.ente.io/gallery#&opened)
```

## Second error - shows "The image could not be loaded" in the center

Console logs:
```
Could not parse HEIF file Invalid input: Unspecified: Metadata not correctly assigned to image
[error] Failed to get renderable blob for IMG_4192.HEIC, will fallback to the original: Error: HEIF image not found
```

### What product are you using?

Ente Photos

### What platform are you using?

Web - Firefox

**Comment by mnvr** [comment]
Thank you for the report. Unfortunately, I am unable to reproduce this with the latest iOS public beta as of today. My best guess is that perhaps it is some particular iPhone model + iOS 18 combinations that trigger it? Or something to do with differences in HDR settings...

But it's all conjecture. If you or someone else who runs into this get interested in helping out further, sending a sample to support@ente.io would help.

**Comment by saibotk** [comment]
Well, i just retried this and it seems to be fixed, maybe via some dependency update? 

Anyway thanks for taking the time to answer :)
