### ISSUE TITLE
[Photos App] Multiple crashes of app

### ISSUE THREAD

**Issue by thfsilvab** [ente-io/ente#3219]
### Description

I've been experiencing the app crash a lot, but especially when uploading big sized files (long videos, for example). I didn't attempt to understand what exactly was happening, but I extracted a log file before the app crashed again.

Device: Samsung Galaxy S23 Ultra
Android Version: 14
One UI Version: 6.1

[2024-9-10.txt](https://github.com/user-attachments/files/16949134/2024-9-10.txt)

### Version

0.9.35

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
There was a regression in the older version of the app. Please upgrade to the latest version. Also. if you are uploading large videos, I would suggest you to enable Resumable Upload from the Backup Settings. If you still face the crash, please feel free to comment on this issue.
