### ISSUE TITLE
Desktop: enter/return does not activate default button in modal dialogs

### ISSUE THREAD

**Issue by sneak** [ente-io/ente#3227]
### Description

When I am, for example, removing an image from a gallery, a modal appears.  When pressing the return key on my Mac, I expect the dialog to be dismissed with the highlighted (default) button.  Instead, the return key does nothing.

### Version

v1.7.4

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - macOS

**Comment by robertsattler** [comment]
Same for Desktop - Linux v1.7.4

+1 on the expectation: Enter to confirm the action, e.g. delete the photo. This would be also really helpful on the workflow of sorting out multiple photos like duplicates or bad photos from burst shots.

Pressing ESC cancels (closes) the modal as expected.
