### ISSUE TITLE
[AUTH] [IMPORTANT] issue with the code list

### ISSUE THREAD

**Issue by kishan-dhankecha** [ente-io/ente#3229]
### Description

When hide codes are turned on and there are multiple tags that can be used to filter the list, there is a bug. See the attached video to know this in action.

Basically, this issue is happening due to how Flutter makes the render tree and widget tree. It can be fixed by simply adding a key to the widget. I will open a PR that fixes this.

https://github.com/user-attachments/assets/626dc476-f7b7-4def-819c-3561b43e8061

### Version

3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS, Mobile - Android, Mobile - FDroid, Desktop - Linux, Desktop - Windows, Desktop - macOS, Web - Firefox, Web - Chrome, Web - Safari, Web - Edge, Server

**Comment by ua741** [comment]
Thank you for the PR @kishan-dhankecha . This change will go in the next release.
