### ISSUE TITLE
Person can't be removed from photo

### ISSUE THREAD

**Issue by FloEdelmann** [ente-io/ente#3255]
### Description

1. Turn on face recognition
2. Assign a person to an image
3. Try to remove that image from that person ("Not [person]?" action)
4. Nothing happens, the image is still assigned to that person.

### Version

v0.9.27

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android, Mobile - FDroid

**Comment by laurenspriem** [comment]
This is an old bug that is already fixed in the latest app version. Unfortunately F-Droid is usually slow to update so it doesn't have this version yet. You can try the latest version from Play Store or GitHub, or wait till the release is on F-Droid.

**Comment by FloEdelmann** [comment]
Thanks for the response!
