### ISSUE TITLE
2FA Website stopped working!

### ISSUE THREAD

**Issue by mrx23dot** [ente-io/ente#3262]
### Description

I follow link from main website https://ente.io/auth  called "Web"
Login

Then it only gives me options:
![2024-09-13_193407_fu](https://github.com/user-attachments/assets/44654ee6-3b3e-4d64-babe-fce5b872d195)

I would expect full 2FA managment functionality as promissed.

### Version

web

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by dnred** [comment]
Right now the web app can only view the codes you have. To edit, delete etc. you have to download their app on desktop or mobile.

You can still view the codes right? If so this shouldn't be an issue but rather a feature request in discussions.

**Comment by ua741** [comment]
Web was always read only. We have a open feature request on discussion to make it fully functional app. Currently, we don't have bandwidth to add additional features on web auth.
