### ISSUE TITLE
Can't manually enter TOTP keys

### ISSUE THREAD

**Issue by mrx23dot** [ente-io/ente#3267]
### Description

I logged into android app,
I click on Enter a setup key
I filled out issuer/TOTP secret key/account
clicked on Save

but nothing is happening, I'm back to main screen.

### Version

3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Hey @mrx23dot,
Can you help us with more details that can help us reproduce this issue?
Does the issuer or account name contain any special character. If you haven't activated the MFA with that particular code, can you share the code with us either here or write to support@ente.io?

**Comment by ua741** [comment]
if you have enabled online back, then for first code do need internet. For now, I will close this issue and add error handling on this screen so that user have some feedback about what went wrong.
