### ISSUE TITLE
[AUTH] [BUG REPORT] Codes are different on different OS's, despite same account

### ISSUE THREAD

**Issue by Scorza9999** [ente-io/ente#3273]
### Description

Hello and thank you for reading this bug report.

This is a pretty serious bug, at least for me, since my only reason for using Ente, compared to other 2FA apps is the fact that the codes are synced.

I discovered this bug while trying to access a website. When I tried to use the codes that are on any version other then the one I enabled 2FA from, it kept telling me that the credentials were incorrect. (E.G. Accessing website X, using the codes on the ente app of device A, is a success, but not on the ones in the app of device B). As previously mentioned, this is despite the fact that the accounts are the same. This means that: on the web, desktop (windows) and android versions _at least_, the codes generated with the same ente account, for the same account, are different. This is, of course, pretty bad.

Unfortunately, I have no idea on how to fix this issue, but it requires patching ASAP, otherwise some users might lose their accounts.

### Version

3.1.3

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - FDroid, Desktop - Windows, Web - Firefox, Web - Chrome

**Comment by andbenn** [comment]
@Scorza9999 this can happen if time drifts on the device.  There's only a 30 second window on the current code as well.  Usually mobiles are on network time and darn close to actual.

Compare the clocks and ensure they are very close.

**Comment by Scorza9999** [comment]
Thank you for helping me troubleshoot, you were right, that was the issue:
On the desktop PC the clock was set (for some weird reason) back by 3 minutes compared to my mobile device.
I just manually set the clock and both the desktop app and website displayed the correct codes (maybe because the website uses the system's clock?).
Thank you for your time
