### ISSUE TITLE
[auth] Trash code text shows brackets when no account name is configured

### ISSUE THREAD

**Issue by sv3nnie** [ente-io/ente#3354]
### Description

Small visual bug: the new trash code text displays brackets where the account name would typically appear, even when no account name is configured. For instance, I only set the issuer name to LinkedIn and left the account name empty, but the brackets are still visible where the account name would be shown if it were configured.
![image](https://github.com/user-attachments/assets/5f326568-8991-442a-8014-6270cf6c2307)

### Version

v4.0.0

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by ua741** [comment]
Thanks, Should be fixed in the next release.
