### ISSUE TITLE
Press and hold menu for authentication code is broken in landscape orientation

### ISSUE THREAD

**Issue by BionicBison05** [ente-io/ente#3368]
### Description

On both an iPhone 14 Pro Max and iPad Pro 11", using Auth in landscape orientation breaks the press and hold menu. See attached screenshots. As a side note, I don't think the options should need to be scrolled through on iPad as there is clearly enough space to display them all like on the iPhone.

Portrait - iPad:
![09293D31-5712-41D5-9F90-F4051D439FF1_1_201_a](https://github.com/user-attachments/assets/06a76f8e-c568-4a55-9d65-669f4d223088)

Landscape - iPad:
![A3B4E5FC-A30F-4803-A7FD-10AD071E129D_1_201_a](https://github.com/user-attachments/assets/9c282686-118e-4485-b67c-5728679ebb40)

Portrait - iPhone:
![791AFD9C-07BC-4326-B122-89F51DC680AA_1_201_a](https://github.com/user-attachments/assets/4eaf1d4b-e1a8-455d-9d87-440326c501bb)

Landscape - iPhone:
![7E2EA601-416A-4FDA-AA27-0F3F5F30F822_1_201_a](https://github.com/user-attachments/assets/0ea01477-38e7-451c-9c50-a656ef612f27)

### Version

4.0.0

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by Gururagavendra** [comment]
@BionicBison05  i love to solve the issue , is there any protocol i need to follow to solve this bug

**Comment by ua741** [comment]
This should be fixed in the latest version 4.0.1
