### ISSUE TITLE
[photos][mobile] Unclear selection on deduplication page

### ISSUE THREAD

**Issue by Trekky12** [ente-io/ente#3369]
### Description

When opening the deduplication page on mobile there is a default selection of images but the image is not highlight and it is therefore unclear which image gets deleted. 
Additionally it is not possible to make a specific selection but only click the checkmark near the duplicates.

### Version

v0.9.41

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - iOS

**Comment by ua741** [comment]
@Trekky12 This is by design. As the files are exact duplicate, mobile client only keeps one copy, and ensure that there's a link of that copy in all albums where duplicates are present.

**Comment by Trekky12** [comment]
@ua741 thank you for the response. This makes sense 👍 But maybe the desktop version needs to be adjusted because with the desktop version one image is preselected and it is possible to change the selection.
