### ISSUE TITLE
[cli] Unable to export authenticator codes: failed to decrypt data: invalid tag

### ISSUE THREAD

**Issue by maxlajoie99** [ente-io/ente#3371]
Using cli-v0.2.0, I am unable to backup my authenticator codes:
> / # ./ente-cli export
[xyz@xyz.com] 2024/09/20 20:23:41 Error fetching entities: failed to decrypt auth enityt f03f6f90-e27f-431b-acfd-e158a5218979: failed to decrypt data: invalid tag

https://github.com/ente-io/ente/blob/405c0c343ff0fdf822c5f2bc8cbab358d10ff38e/cli/pkg/mapper/authenticator.go#L12

Looking a bit at the code, I feel like it should be `eCrypto.DecryptChaChaBase64Auth(...)` instead

**Comment by ua741** [comment]
Hey @maxlajoie99 , Can you please check if you are facing this issue in the latest version?

**Comment by maxlajoie99** [comment]
It is working using cli-v0.2.1, thank you!
