### ISSUE TITLE
Auth app not starting on Linux

### ISSUE THREAD

**Issue by luleyleo** [ente-io/ente#3378]
### Description

I've installed the Auth app with the latest RPM release. When I try to start the app, I get the following error message:

```text
flutter:  [ente_logging] [INFO] [2024-09-21 10:28:03.577883] log file for today: File: '/var/home/leopold/.local/share/ente_auth/logs/2024-9-21.txt' with prefix 
flutter: [ente_logging] [INFO] [2024-09-21 10:28:03.577883] app version: '3.1.3+323'
flutter: [ente_logging] [INFO] [2024-09-21 10:28:03.577883] 
flutter:  [main] [INFO] [2024-09-21 10:28:03.577936] Starting app in foreground
flutter:  [Configuration] [INFO] [2024-09-21 10:28:03.588278] Skipping temp folder clear

(ente_auth:4739): Gdk-CRITICAL **: 10:28:03.610: ../gdk/wayland/gdkdisplay-wayland.c:1433: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
[1]    4739 segmentation fault (core dumped)  ente_auth
```

I'm using Fedora, Wayland and have a fractional scale of 1.25. If I disable fractional scaling (so a scale of 1.0) I still get this:

```text
flutter:  [ente_logging] [INFO] [2024-09-21 10:34:39.982482] log file for today: File: '/var/home/leopold/.local/share/ente_auth/logs/2024-9-21.txt' with prefix 
flutter: [ente_logging] [INFO] [2024-09-21 10:34:39.982482] app version: '3.1.3+323'
flutter: [ente_logging] [INFO] [2024-09-21 10:34:39.982482] 
flutter:  [main] [INFO] [2024-09-21 10:34:39.982533] Starting app in foreground
flutter:  [Configuration] [INFO] [2024-09-21 10:34:39.990151] Skipping temp folder clear
[1]    5633 segmentation fault (core dumped)  ente_auth
```

### Version

3.1.3+323 and 4.0.0+400

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by luleyleo** [comment]
> I use fedora 40 gnome wayland and version 4.0.0 works for me after the mentioned fix [here](https://github.com/ente-io/ente/issues/2326#issuecomment-2302392623).

That didn't help, sadly. The `shared_preferences.json` file didn't even exist. And after creating it with values for height and width, I still get the same error.

The app does work on my Laptop though, where I'm running the same system but at 1080p and no fractional scaling. My PC has 4k and fractional scaling, so maybe that causes issues.

**Comment by gelbphoenix** [comment]
> That didn't help, sadly.

Have you also looked in `~/.local/share/ente_auth/` instead of `.local/share/io.ente.auth/`? Fractional scaling could be a problem but can't really tell for now.

**Comment by gelbphoenix** [comment]
> Fractional scaling could be a problem but can't really tell for now.

_Need verification and possibly a new issue._

Enabled fractional scaling opens Auth in a maximized window. After a few times the values in `shared_preferences.json` are overwritten and the app doesn't start.

**Comment by m0byn** [comment]
I can confirm the issue. Already had the problem of ente auth not starting some days ago. Then, I tried the mentioned fix [here](https://github.com/ente-io/ente/issues/2326#issuecomment-2302392623), and everything worked fine. Yesterday, I uninstalled ente auth and reinstalled it from flathub to have regular updates. Unfortunately, after several times starting, the app won´t start up anymore. The mentioned fix does not help as all the values for height and with are set to 500.

**Comment by gelbphoenix** [comment]
> I can confirm the issue. Already had the problem of ente auth not starting some days ago. Then, I tried the mentioned fix [here](https://github.com/ente-io/ente/issues/2326#issuecomment-2302392623), and everything worked fine. Yesterday, I uninstalled ente auth and reinstalled it from flathub to have regular updates. Unfortunately, after several times starting, the app won´t start up anymore. The mentioned fix does not help as all the values for height and with are set to 500.

The file for the Flatpak package is not in `$HOME/.local/share`.
I mentioned it already in the issue you've linked. https://github.com/ente-io/ente/issues/2326#issuecomment-2408616899

**Comment by m0byn** [comment]
> The file for the Flatpak package is not in `$HOME/.local/share`. I mentioned it already in the issue you've linked. [#2326 (comment)](https://github.com/ente-io/ente/issues/2326#issuecomment-2408616899)

Oh damn...I did not know that. Just checked and yes, it was a very large number at height. So, for me the issue is resolved - THANK YOU!

**Comment by luleyleo** [comment]
I re-installed Fedora for unrelated reasons, and somehow I no longer have this issue. I still have no idea, where it came from, but given that I can't reproduce it anymore, I'm going to close this.

**Comment by gelbphoenix** [comment]
> I re-installed Fedora for unrelated reasons, and somehow I no longer have this issue. I still have no idea, where it came from, but given that I can't reproduce it anymore, I'm going to close this.

I guess the fractional scaling was a problem. See: https://github.com/ente-io/ente/issues/3378#issuecomment-2395077969
