### ISSUE TITLE
[Ente Photo] Unable to open iPhone 16 photos on Windows Desktop

### ISSUE THREAD

**Issue by iamdangry** [ente-io/ente#3391]
### Description

Uploaded an image from my iPhone 16 to Ente

Within the iOS app and web app, I can open the image fine.

On windows desktop, opening the image results in an error "The image cannot be loaded"

![image](https://github.com/user-attachments/assets/4a8cf3d3-6f2d-4e24-a929-357c6d590d4c)

Image is HEIC

My previous iPhone 12 also shot HEIC and those images are unaffected. Only new images taken on the 16 can't be opened.

I can download the image from within the Ente Photos desktop app and open the images open fine.

### Version

1.7.4

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - iOS, Desktop - Windows, Web - Firefox

**Comment by mnvr** [comment]
https://github.com/ente-io/ente/issues/3186#issuecomment-2350912507

**Comment by mnvr** [comment]
Also, if it opens in the web app but not in the desktop app, it has already likely been fixed in the [nightly beta builds](https://github.com/ente-io/photos-desktop/releases)

**Comment by iamdangry** [comment]
Looks that way. Just installed 1.7.5-beta and I can open the images
