### ISSUE TITLE
Windows ARM64 support

### ISSUE THREAD

**Issue by gratianlup** [ente-io/ente#3405]
### Discussed in https://github.com/ente-io/ente/discussions/3404

<div type='discussions-op-text'>

<sup>Originally posted by **gratianlup** September 22, 2024</sup>
Tried to install the app on one of those new ARM64 Windows laptops and the setup reported it's not a supported architecture.
If not a native ARM64 build, could at least the setup be changed so it allows the install and the app would run through emulation then (most likely it should be fine).

Thanks!</div>

**Comment by ua741** [comment]
Hello, We will continue tracking feature requests on Github Discussions.
