### ISSUE TITLE
Long left click on Ente Auth item displays unreadable message on Mac OS Sequoia

### ISSUE THREAD

**Issue by SenorNaddy** [ente-io/ente#3410]
### Description

When holding down the left mouse button on an item in the following message is displayed at the bottom of the screen

![image](https://github.com/user-attachments/assets/b2722301-26dd-4f0a-9ec1-d41e89126fd5)

### Version

4.0.0

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - macOS

**Comment by ua741** [comment]
We are tracking this issue here
https://github.com/ente-io/ente/issues/3368
