### ISSUE TITLE
The incorrect codes are being displayed for search results on the iOS Auth app.

### ISSUE THREAD

**Issue by lasofeli** [ente-io/ente#3441]
### Description

I've noticed that when I search for a login in the iOS auth app, the app does not "refresh" the codes it displays for the rows. It does filter the entries and does show me the one I'm searching for, but the code being displayed for that entry is the same as if I didn't search at all.

So if Entry 1 on start-up has code 000 000, and I search for Entry 10, the app displays Entry 10 with the code 000 000. The same behavior occurs for all the rows visible, and the behavior is the same for both the current and the "next code". It only resets when the bar drains/the timer ticks over.

This is on iOS 18, iPhone 13 Pro Max.

### Version

4.0.0

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by ua741** [comment]
This should be fixed in v4.0.1.
