### ISSUE TITLE
[Auth] Token Options Menu Broken in Landscape on iPad

### ISSUE THREAD

**Issue by Damariobros** [ente-io/ente#3454]
### Description

When you hold down on a token to bring up the options menu, if you are in landscape orientation it is broken.
![IMG_0951](https://github.com/user-attachments/assets/5b986d74-72a8-4d4e-baf2-3829bda31740)

### Version

4.0.0

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by ua741** [comment]
Please update your app, it should be fixed in the latest version.
