### ISSUE TITLE
Typo in Privacy Policy (Section 8.4)

### ISSUE THREAD

**Issue by Watchmanq** [ente-io/ente#3463]
### Description

This is probably not the correct place to put this, but nevertheless I found a small grammatical error in Section 8.4 of the privacy policy. There's a minor repetition where the phrase "will not will disclose" appears instead of "will not disclose." It's a minor issue but worth correcting attached is an image circling it to make it easier to find the issue.

![Ente Grammar Issue](https://github.com/user-attachments/assets/1cf19c9f-850c-492c-94e9-2fcfb7d19fb9)

**Comment by vishnukvmd** [comment]
Thanks, fixed!
