### ISSUE TITLE
Fritzbox icons not being displayed

### ISSUE THREAD

**Issue by SpeeterYT** [ente-io/ente#3525]
### Description

If the issuer is set to "FritzBox 7590" no icon is displayed, even though it is in custom-icons.json.
"MyFRITZ!Net" works...

` {
      "title": "MyFRITZ!Net",
      "slug": "myfritz"
      "altNames": [
        "MyFRITZ!",
        "FritzBox",
        "Fritz!Box",
        "FritzBox 7590",
        "FritzBox 7590 AX",
        "FritzBox 7530",
        "FritzBox 7530 AX",
        "FritzBox 4040",
        "FritzBox 4060",
        "FritzBox 5530 Fiber",
        "FritzBox 6490 Cable",
        "FritzBox 6590 Cable",
        "FritzBox 6591 Cable",
        "FritzBox 6660 Cable",
        "FritzBox 6820 LTE",
        "FritzBox 6850 LTE",
        "FritzBox 6850 5G",
        "FritzBox 6890 LTE",
        "FritzBox 7583",
        "FritzBox 7520",
        "FritzBox 7490",
        "FritzBox 7583"
      ]`

### Version

4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows

**Comment by sv3nnie** [comment]
There is an issue with the JSON structure. There is no comma after ``slug``, which means it won't read any of the ``altNames``. The correct format should include a comma to separate the ``slug`` key-value pair from the ``altNames`` key.
