### ISSUE TITLE
Connect to Postgres via SSL

### ISSUE THREAD

**Issue by jlxq0** [ente-io/ente#3568]
### Description

I have an external Postgres DB that I want (have) to connect to via SSL. Is there an environment variable like ENTE_DB_HOST etc., that allows this?
Alternatively, can I pass a whole Postgres URL as an env var?

### Version

v0.9.46

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by ahxxm** [comment]
according to the [source code](https://github.com/ente-io/ente/blob/b26e3b31d816de0e4f27ce2a7b70056729971c64/server/pkg/utils/config/config.go#L112C20-L112C30), you could set `sslmode: required` in `db` section

**Comment by jlxq0** [comment]
Works like a charm. Thank you!

**Comment by addisonklinke** [comment]
For the 3rd party Helm chart from `l4gdev`, there's a values option for [`museum.config.db.sslmode: "require"`](https://github.com/l4gdev/helm-charts/blob/fca224fdd5a29df63e97856ac411ae9e4ef7d6e3/charts/ente-photos/README.md?plain=1#L269)
