### ISSUE TITLE
Request for New Language Translation

### ISSUE THREAD

**Issue by Gateway31** [ente-io/ente#3580]
Language name: Lithuanian (lietuvių kalba; LT)
Project: auth/photos-web/photos-mobile

I actually requested before, on Crowdin few days ago, for ente Photos web/desktop (see https://crowdin.com/project/ente-photos-web/discussions/40), but I thought I might request it here as well and translate both ente Photos and Auth too.

**Comment by mnvr** [comment]
Added! 🇱🇹 Thank you 🙏
