### ISSUE TITLE
[Auth] [Photos] Problem opening ente auth and ente photos in one account, problem not being able to log in to ente auth account due to single two-step verification setting

### ISSUE THREAD

**Issue by universish** [ente-io/ente#3588]
### Description

I had an ente photos app account, i was using totp to log into the account. today i tried to open an ente auth account with the same email address. But it said i already had an account. My ente auth account and my ente photos account were linked. I tried to log into the ente auth account with the ente photos password. then it asked for a two-step verification code. I entered the totp code of the ente photos account, it logged in. Then I changed the password of ente auth in the settings. the password of ente photos also changed. i realized that I will log in to two separate applications with the same account. No problem. but in the settings of ente auth, in the Security section, Email verification (two-step verification) is turned off, off. I logged out of the account. When I tried to log in again, it asked for a totp code. If all my totp codes were in my ente-auth account, I would never be able to enter the account. The problem is that since two-step verification is active in the ente account (ente photos account), it also asks for that code in the ente auth account. For security reasons, I need to turn on two-step verification in the ente photos application.  But it has to be turned off in ente auth account so that i can login to ente auth account. I either have to use two authenticator apps. One is ente auth and the other is another app. In the second app I have to get the ente auth totp code so that I can login to ente auth app with this code. this is a very tedious, very boring app. So I have to turn off two-step verification (email verification) in ente auth app. ente auth asks for totp when logging in even though two-step verification is turned off. because the two apps use the same account and ente photos has two-step verification turned on, ente auth also asks for totp. Because two-step verification is on in ente photos app. Please either create two separate accounts for the two apps; or create two separate identities and settings profiles in one account. If there are two separate accounts. We can also change the passwords, I don't want two apps to have the same password. Using the same password is a security risk. Or we can create two identities or two profiles in one account. ente auth identity and settings can be different, ente photos identity and settings can be different; we can also make the passwords different. This way we can activate two-step verification to the account or profile we want.

### Version

all versions

### What product are you using?

Ente Photos, Ente Auth

### What platform are you using?

Mobile - Android, Mobile - FDroid, Desktop - Linux, Desktop - Windows, Web - Firefox, Web - Chrome

**Comment by ua741** [comment]
You can create account with different email or use alias if you want different password/
https://help.ente.io/auth/faq/enteception/#enteception
