### ISSUE TITLE
Import error in desktop application

### ISSUE THREAD

**Issue by ahmetozmtn** [ente-io/ente#3591]
### Description

The "Scan a QR Code" button does not appear when importing "Google Authenticator" codes.

![image](https://github.com/user-attachments/assets/beb265f0-6408-45b5-8ca0-50de0722e575)

### Version

v4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by prateekmedia** [comment]
QR Scanning is unsupported on desktop.
