### ISSUE TITLE
Photos in an album from magic search starts displaying results at different points.

### ISSUE THREAD

**Issue by zoom6453** [ente-io/ente#3603]
### Description

Problem:
When i perform a magic search and select the result, the album will start in the middle or at the end depending on how far down i scrolled on the previous page.
For example if i'm in my 'All' album, and i scroll down a decent amount. If i then do a magic search and select it, the magic search album won't start at the top, it will start scrolled down and I have to scroll back up to get to the top of the results.

So it seems the position of the scroll bar in the normal albums has an affect on the position of the scroll bar in the magic search.

Expected behaviour:
Magic search album displays results starting at the top

### Version

v1.7.5

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Linux

**Comment by mnvr** [comment]
Thank you for reporting this. Fix will be in the next [nightly build](https://github.com/ente-io/photos-desktop/releases) (will get built in a few hours), and of course, it'll also be in the next regular release.
