### ISSUE TITLE
Using back gesture after dismissing image share quits the app 

### ISSUE THREAD

**Issue by zoom6453** [ente-io/ente#3613]
### Description

Problem:
When I'm viewing an image/video, and I press the share icon, but then i dismiss it. If i then use the android back gesture (swipe from the side in my case) it will quit the app and take me to the home screen.

Expected behaviour: 
Using the back gesture will take me to the previous screen in the app, like it does when I don't press the share icon. 

### Version

0.9.46

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by mackid1993** [comment]
This drives me crazy too! It's not the way Android apps are supposed to work.

**Comment by zoom6453** [comment]
I've also noticed when you delete an image or empty the trash, the back gesture will cause you to quit the app as well.

**Comment by brog-io** [comment]
Yeah this is annoying, it should just cancel
