### ISSUE TITLE
enhancement request was closed/ignored without explaination...

### ISSUE THREAD

**Issue by asanghc** [ente-io/ente#3625]
### Description

https://github.com/ente-io/ente/issues/3359

### Version

all

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Linux, Desktop - Windows

**Comment by vishnukvmd** [comment]
Issues are for bug reports. Please use [Discussions](https://github.com/ente-io/ente/discussions/) for feature requests.

<img width="596" alt="Screenshot 2024-10-08 at 7 21 50 PM" src="https://github.com/user-attachments/assets/065d6ce4-09de-4b4d-a2ee-09c7f2921bac">
