### ISSUE TITLE
Request for New Language Translation

### ISSUE THREAD

**Issue by Nollasko** [ente-io/ente#3634]
Language name: Ukrainian / Українська
Project: photos and web

**Comment by mnvr** [comment]
Added! Thank you 🙏

**Comment by Nollasko** [comment]
@mnvr Hello. It is not showing in android app language selection. And it should start capitalised. "Українська"
![image](https://github.com/user-attachments/assets/13a1e1b7-d0cb-46e8-a939-e4982488f07c)

**Comment by mnvr** [comment]
Thank you for spotting this. I've fixed the capitalization of "Українська" (the change is deployed to the web version, and will be part of the next desktop app release).

Re: not being able to see the option in the mobile app - the mobile app is updated and released separately, so these language changes will be part of the next release of the mobile app.

**Comment by mnvr** [comment]
This will go out in next release https://github.com/ente-io/ente/pull/4223
