### ISSUE TITLE
Initiate search by clicking where search field will be

### ISSUE THREAD

**Issue by kenmanheimer** [ente-io/ente#3678]
### Description

Please make clicks on where the search box will be activate search. This could be in addition to or instead of having to click on the magnifying glass.

On the Windows app this spot is occupied by the app title (except when search mode is active). While that's useful, there is currently no effect that I see from clicking on the app title, and it would be consistent with many applications to have it activate search mode. So much so that I tend to assume doing so will go straight to search mode, even though I've made the mistake several times before. I'm probably not the only one.

### Version

v4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Tracking this issue here: https://github.com/ente-io/ente/discussions/3153
