### ISSUE TITLE
Auth : Codes

### ISSUE THREAD

**Issue by Bayleyvilla** [ente-io/ente#3686]
### Description

Greetings.
I have tried to use Auth today and every code is being rejected.
This is a major problem as all items that require a code are rejecting the codes provided by Auth
I have tried to add a new code this is also being rejected when presented

Update ( the codes on android are different to the codes on PC windows )

Update 2 ( the android codes seem to be correct Windows codes are incorrect )

Update 3 ( auth on line https://auth.ente.io/auth codes are the same as desktop and fail to work )

### Version

4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows

**Comment by mnvr** [comment]
https://help.ente.io/auth/faq/#why-do-the-desktop-and-mobile-apps-display-different-codes

**Comment by Evren-os** [comment]
I’m having the same issue with ente-auth on both Android and Windows. When I try logging into sites from my browser on Windows using the code from the Windows ente-auth app, it gets rejected—like it says the code doesn’t match what’s on the Android version. But when I use the code from the Android app, it works just fine. Anyone know why this is happening?

**Comment by Bayleyvilla** [comment]
This problem seems to have resolved its self.
The time and date were checked on all installed units ( and found to be correct )
Please note that at the time the problem was encountered  https://auth.ente.io/auth was also providing codes that failed to work
To conclude this problem resolved itself with no end user intervention.

**Comment by Evren-os** [comment]
> This problem seems to have resolved its self. The time and date were checked on all installed units ( and found to be correct ) Please note that at the time the problem was encountered https://auth.ente.io/auth was also providing codes that failed to work To conclude this problem resolved itself with no end user intervention.

Yes, after trying with ente auth in android, the web version and desktop app worked
