### ISSUE TITLE
Icons are not visible

### ISSUE THREAD

**Issue by vict75** [ente-io/ente#3703]
### Description

Hi, 
Unzipped ente-auth-v4.0.2-windows and got this look:
![image](https://github.com/user-attachments/assets/cdeab86f-35d3-4aa3-bc0e-088b9ae792d5)

### Version

v4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Can you be specific which icon is missing? I am unable to pin point at the problem.

**Comment by vict75** [comment]
Update: I tried the ente-auth-v4.0.2-installer.exe version and that one works fine with icons all visible. Possibly it is related to the packaging. When I startup the unzipped 4.0.2 version the icons are missing again.
