### ISSUE TITLE
Certificate Verification Fails, Cannot Open Webpage.

### ISSUE THREAD

**Issue by natejw** [ente-io/ente#3766]
### Description

https://github.com/ente-io/ente/discussions/3590 (it directed me there but i didnt get it answered)

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by lotusflowr** [comment]
Same issue.
<img width="289" alt="{1CF1C639-559A-460B-AE68-F38D1D9933D5}" src="https://github.com/user-attachments/assets/92ae296e-76b3-488c-a4dc-622a3f5b9a3c">

**Comment by ua741** [comment]
Please refer to following doc: https://help.ente.io/auth/troubleshooting/windows-login
