### ISSUE TITLE
[Auth] In Ente Auth in fedora 40 OS, when I click on the search icon, the cursor does not appear in the search box, I have to click on the search box to type

### ISSUE THREAD

**Issue by universish** [ente-io/ente#3824]
### Description

In Ente Auth in fedora 40 OS, when I click on the search icon, the cursor does not appear in the search box, I have to click on the search box to type. I don't have this problem in Windows, I have this problem in fedora.
I first installed ente auth v4.0.2 on fedora 40. I reported in this URL that I thought this feature was missing and needed to add a new feature:
https://github.com/ente-io/ente/issues/3699
Then I installed v4.0.2 auth on Windows 11. I noticed that it has this feature. When you click on the search icon (magnifying glass icon) the cursor is active in the search box and you can search. When I saw this I realized that this is a problem for ente auth on fedora, that's why I'm reporting this problem.
The same problem persists in v4.0.3-beta.5.

### Version

v4.0.2 and v4.0.3-beta-5

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux, Desktop - Windows

**Comment by huonw** [comment]
This may be the same as https://github.com/ente-io/ente/issues/3331
