### ISSUE TITLE
[Ente auth] Activating search on app startup does not activate keyboard

### ISSUE THREAD

**Issue by bobf32** [ente-io/ente#3849]
### Description

Hi. Mobile user here. Have enabled the setting to Focus search on app start. This technically does what I would expect, i.e. puts focus in the search bar on app startup, but it does not activate the keyboard. Net result is I still have to tap in the search box for the keyboard to appear so I can enter some search text. 

I would expect the phone's keyboard to activate after starting the app with the Focus search on app start setting enabled.

### Version

4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by pc-v2** [comment]
Also happen in Windows, I can't type to any input field (eg. PIN and Search)

**Comment by UjjwalSharma01** [comment]
im also facing the same issue

**Comment by mMosiur** [comment]
Same problem here, I tried clearing app cache but it did not help. The problem also occurs when clicking the search button inside the app, without the "focus search on app start" option - the keyboard only appears after pressing the "Search..." field

**Comment by ChristopherW** [comment]
This behaviour is still present in the latest Android, and seems related to how the soft keyboard does not appear when tapping on the search icon in the top-right - it also still requires a tap inside the text box to show the keyboard. 

This is not great UX - I would expect that tapping the search box should put the caret in the text box and simultaneously show the keyboard, but it always requires a second tap inside the text box. This is also the case if you have the 'focus search on app start' enabled.

**Comment by RedPeace** [comment]
Same problem here. Latest app and android version.

**Comment by ua741** [comment]
Tapping on search icon should automatically bring up the keyboard. If someone is still facing this issue, please confirm your app version.

**Comment by ua741** [comment]
> Yes, tapping on the search icon works now 👍 But the original issue, not showing the keyboard on app start, still persists for me (Android, 4.1.6).

Thanks for confirming. We are tracking the other issue here https://github.com/ente-io/ente/issues/279#issuecomment-2184533589
