### ISSUE TITLE
[Auth][Android][Bug] Deleting a code doesn't work

### ISSUE THREAD

**Issue by RestedCoriander** [ente-io/ente#3860]
### Description

When I try to delete a code it just does nothing, it acts like I didn't even press it. I have tried this on other versions, e.g v4.0.2, playstore version, f droid version, github version. None of them fixed the issue.

### Version

v4.0.3-beta.5

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Mobile - FDroid

**Comment by ua741** [comment]
If you don't any kind of device lock enabled on your decide, you might run into above issue. To confirm this, can you try to edit the code. If our assumption is correct, that operation should also silently fail.

PS: You can go to Security-> App Lock section within your Ente Auth app, and enable App Lock. This should ideally fix this issue.
