### ISSUE TITLE
[Auth] "altNames" for custom icons are not being recognized

### ISSUE THREAD

**Issue by KingLuc12** [ente-io/ente#3875]
### Description

If I change the name of my account to something other than the title of the custom icon and instead use an "altName" of the account, the custom icon will not be displayed.

### Example(s):

**Custom Icon config:**
`{
      "title": "Ubiquiti",
      "slug": "ubiquiti",
      "altNames": [
        "Unifi SSO",
        "Unifi",
        "Ubiquti SSO"
      ]
    }`
    
**Account using "title":**
![image](https://github.com/user-attachments/assets/067b1d68-210c-403a-8b71-c4e7b84271e0)

**Account using one of the "altNames":**
![image](https://github.com/user-attachments/assets/a0e790a2-0d1b-48fd-b0ca-9ef408ed11aa)

### Expected behaviour:

The icon for the account should always be the Ubiquiti logo, as the other names are defined as altNames.

### Version

v4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS, Mobile - Android, Mobile - FDroid, Desktop - Linux, Desktop - Windows, Desktop - macOS

**Comment by LeGenDaRy15PT** [comment]
How did you manage to test the icon on yours? 

I put several icons that I didn't have on mine and it still doesn't detect me.

**Comment by KingLuc12** [comment]
> How did you manage to test the icon on yours?
> 
> I put several icons that I didn't have on mine and it still doesn't detect me.

I'm not quite sure what you mean by this.

**Comment by LeGenDaRy15PT** [comment]
Sorry for my English
I meant how did you manage to see the icon through the app, the icons that I added I still don't see in the app

**Comment by KingLuc12** [comment]
Are you definitely using the custom icon's "title" as the issuer name

**Comment by LeGenDaRy15PT** [comment]
I left it as per the "title" and still the icon doesn't appear
![imagem](https://github.com/user-attachments/assets/bec04414-b73e-4df9-b9ff-ed349dc827a3)
