### ISSUE TITLE
Export Data Encrypted - keyboard input does not work

### ISSUE THREAD

**Issue by petardo1** [ente-io/ente#3896]
### Description

Export Data Encrypted - keyboard input does not work. I can input password only by right click / paste.
Edit: putting on tray and back solves the problem.
It seams to be a getting focus problem.

### Version

4.0.3

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Dupe of https://github.com/ente-io/ente/issues/2262
