### ISSUE TITLE
auth doesn't properly compute/calculate/display ya-otp

### ISSUE THREAD

**Issue by asanghc** [ente-io/ente#4016]
### Description

ya-otp should be letters, not numbers...

### Version

4.1.0

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Mobile - FDroid, Desktop - Linux, Desktop - Windows

**Comment by ua741** [comment]
Tracking this feature request here: https://github.com/ente-io/ente/discussions/3366
