### ISSUE TITLE
Galaxy A52 can't import encrypted export

### ISSUE THREAD

**Issue by digitalfredy** [ente-io/ente#402]
**Describe the bug**
I deployed auth to 35 users and one of them was not capable to import the ente auth encrypted exported json file because he got:

> can not parse json file

We know is not a file issue because we imported that same file in another phone and it works.

The user updated his OS to the latest version available.

**To Reproduce**
1. auth fresh intalled
2. Click on Import codes / ente Encrypted export / Select JSON file 
3. Select file in the phone file manager
4. User get the `can not parse json file` error

**Expected behavior**
File should be imported

**Screenshots**
![auth-can-not-parse-json](https://github.com/ente-io/auth/assets/1372919/24300f5f-c8aa-4840-9c53-886e29d4b538)

**Smartphone (please complete the following information):**
 - Device: Galaxy A52  (model: SM-A525M/DS)
 - OS: Android
 - Version: 13

**Comment by ua741** [comment]
This is strange, especially if this works on one device but doesn't work on another.

Can you confirm if the app prompted the user for the password or it failed before that?
Also, can you please enable logs from Settings -> General -> Crash & Reporting and repeat the process again?

Post that, it will be great if you can share the error logs (Settings-> Support -> Report logs) with us at support@ente.io.

Sorry for the trouble.

**Comment by digitalfredy** [comment]
I asked the end user (not a dev) to try to answer to your message here.

Thanks

**Comment by juandebrigard** [comment]
Hey, there! I'm the end user experiencing the problem.

It failed before asking for the password. On the first try, it didn't import the codes, but it also did not display the error message, I tried it again and on the second try, it displayed the message ("can not parse selected file").

I've sent over the logs from today. Hope they're useful.

If there's anything else you need, please let us know.

**Comment by vishnukvmd** [comment]
Hey @juandebrigard, could you please reproduce the issue once and then re-share the logs?

Sorry for the troubles, and thank you! 🙏

**Comment by digitalfredy** [comment]
Closing because requested logs were not provided.
