### ISSUE TITLE
Ente Auth Windows on Windows ARM not working (At logging in: Certificate Failure message)

### ISSUE THREAD

**Issue by hardinxcore** [ente-io/ente#4043]
### Description

After installing in on Windows on Arm, after starting and trying logging in for the first time, got the error message "Certificate verification failed. Please update your system certificates, & restart the app. If the issue persists, please contact support."

All up to dat on new laptop with Win1124H2 on Snapdragon (ARM) SOC.

### Version

4.1.0

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment]
Please follow these steps https://help.ente.io/auth/troubleshooting/windows-login
