### ISSUE TITLE
Maschine Learning indices do not sync 

### ISSUE THREAD

**Issue by Simon67855** [ente-io/ente#4055]
### Description

I indexed all my pictures on my pixel 6, Graphene OS, worked fine.

Enabling ML on my wifes iPhone, the indices where not synced, it started from scratch. I left it in this state for weeks, it could not finish indexing and it did not sync Form the Android APP.

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - iOS, Mobile - FDroid, Desktop - Linux

**Comment by simondubrulle** [comment]
Hi, are you using the same account on the iPhone? Or is it a different account accessing the same photos/album?

**Comment by Simon67855** [comment]
Hi, it is a different account. Do I have to use the same?

**Comment by laurenspriem** [comment]
Right now ML sync is only within the same account. We are planning to add partner/shared sync in the future.
