### ISSUE TITLE
After updating the Windows app ALL codes are gone!!

### ISSUE THREAD

**Issue by Trustwbc** [ente-io/ente#4101]
### Description

I was offered an update within the Windows app, which I installed from Github. Through my seed phrase I am logged back into my account, I see that my email address is displayed, but... ALL 2FA codes are gone!!! HELP

### Version

4.1.0

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by bithack3r** [comment]
Same thing with me. Just updated and relaunched the app to see it's empty and asking me to add first account. 
Windows 10

**Comment by MightyGadget** [comment]
I have the same problem. Thankfully, I have the mobile app installed, so I was able to export my code as a backup measure.

**Comment by wbonbon** [comment]
same, for some reason it didn't sync automatically.
I tried logout and re-login, synced.

**Comment by DrWheelicus** [comment]
I also updated yesterday, and the same thing happened. This is extremely frustrating!

**Comment by prateekmedia** [comment]
You can logout and login to resync the codes. This issue is due to the migration that's happening and maybe it went unsuccessful.

**Comment by prateekmedia** [comment]
Also can you confirm that were you using a stable release before or beta version?

**Comment by wbonbon** [comment]
I checked the installer I downloaded previously and the file name was ente-auth-v4.0.3-beta.5-installer.exe
It's a beta version.

**Comment by Trustwbc** [comment]
Logoff and login after Update solved the Problem! Thanks a lot!

**Comment by prateekmedia** [comment]
**NOTE:** Those still facing issues and have not login, logout to fix it already can use the following version:

[ente-auth-v4.1.1-nightly.1-installer.zip](https://github.com/user-attachments/files/17876324/ente-auth-v4.1.1-nightly.1-installer.zip)

It will migrate the codes, as migration of codes failed for people using v4.0.3 beta 5 

Those who want to verify the SHA of the exe inside the zip can refer to this:
[sha256sum-windows.txt](https://github.com/user-attachments/files/17876332/sha256sum-windows.txt)
