### ISSUE TITLE
First account?

### ISSUE THREAD

**Issue by MarSOnEarth** [ente-io/ente#4175]
### Discussed in https://github.com/ente-io/ente/discussions/4174

<div type='discussions-op-text'>

<sup>Originally posted by **MarSOnEarth** November 25, 2024</sup>
Upon updating the Windows app to 4.10 I'm presented with "Setup your first account" with enter a setup key! What key!!!

The app is logged in to my account, but I cannot access my codes! I'm locked out of my codes just when I need them.  This shouldn't be happening!</div>

**Comment by ua741** [comment]
You can either logout and login again or [install this build[l](https://github.com/ente-io/ente/issues/4101#issuecomment-2494789267). There was a recent regression, which only affects people who had installed Beta version of the Windows auth app. 
Sorry for the trouble.

**Comment by MarSOnEarth** [comment]
No need. Thank you for a quick turnaround.
