### ISSUE TITLE
Some strings are not localized

### ISSUE THREAD

**Issue by Andypsl8** [ente-io/ente#4262]
### Description

Some strings are not localized for Ente Auth app on Android:

`Theme`
`Light`
`Dark`
`System`

These strings do not appear in the Crowdin project.

### Version

4.1.0

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
<img width="322" alt="image" src="https://github.com/user-attachments/assets/9fed5a24-314a-4461-9212-e02bc2d34a17">
The strings are on crowdin, search for following keys
"theme",  "lightTheme" "darkTheme", & "systemTheme"

**Comment by Andypsl8** [comment]
> <img alt="image" width="322" src="https://private-user-images.githubusercontent.com/254676/391220940-9fed5a24-314a-4461-9212-e02bc2d34a17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NTM2NTEsIm5iZiI6MTczMjk1MzM1MSwicGF0aCI6Ii8yNTQ2NzYvMzkxMjIwOTQwLTlmZWQ1YTI0LTMxNGEtNDQ2MS05MjEyLWUwMmJjMmQzNGExNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwNzU1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzAzMjRmNzQxZWIwZjU2M2UyMTgwMTM3NTM2OGQyZTVlZDVkMmMwMjIyMzkyYTQwYWNjYmNmMGUxM2VkY2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h9eGVLc60kUYK9I-Wd2o2Qz4A7RO4Wa0fayGBcUmZUQ"> The strings are on crowdin, search for following keys "theme", "lightTheme" "darkTheme", & "systemTheme"

Can you send me the link? I can't find them.
