### ISSUE TITLE
Hidden photos still displayed in albums tab

### ISSUE THREAD

**Issue by inomfood** [ente-io/ente#4273]
### Description

**Current Behavior**
When a photo or album is hidden, it is still visible front and center in the "On Device" section of the albums screen. The only way to stop it from being diplayed is to delete the photo or album from your device completely. 

**To reporoduce:**
1. Back up an image in the Ente android client
2. Hide the image
3. Look at the albums tab. The hidden image is displayed at the top of the screen in the section marked "On Device"
![Screenshot_20241201-131212_1](https://github.com/user-attachments/assets/1bc4936c-9a67-46be-8ca0-f05b91b3f7ea)

**Expected Behavior**
When a photo or album is hidden, it should not be visible outside of the "Hidden" area in the app. 

### Version

0.9.65

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
On Device will always reflect what's available/visible `On Device` in your phone, visible to other apps. Not hiding is by design, to ensure that user don't get incorrect idea that the photo is hidden from other system apps.
