### ISSUE TITLE
[mob][Photos] CreationDate gets (randomly?) changed when downloading remote photo/video

### ISSUE THREAD

**Issue by simondubrulle** [ente-io/ente#4296]
### Description

It is now the second time in only a few trials that this behaviour occurs. 

Whenever I download remote files that are in my timeline (and not from a public shared album) but not yet on my device, the files get propely downloaded in the "Pictures" folder (assets are created) but some of the tiles will (likely) move to the top of the timeline in the "today" section. Looking at the photos info, the creation time is now today (at the time of the download). If I check the web app, it will also appear in the "today" section, like if it has been changed in the DB as well.

**Steps to reproduce :**

0. Delete application cache (to make sure the remote files are not cached somewhere)
1. From the timeline, or from an album view, Multi select files which you know are not yet on your device (and let's assume photos were taken in 2019)
2. Click "Download" from the selection tab and let it download them all
3. Some of them will "likely" have their creation time changed to today, at the time you clicked the download button
4. You will therefore find some of these downloaded photos in "today" section of the album/timeline.

**Expected behaviour :**
Since Ente was already "aware" of the correct date, it should not change it when I download the photo locally.

**Extra info :**
I also noticed that in the "Pictures" album (which is not selected for backup), some of the downloaded photos will have the proper creation date assigned (in 2019, for example) but most of them will be in the "Today" section as well. At first I thought it was only pictures with no EXIF data but I can find some with Exif data as well. Actually, some photos from the same moment (few seconds apart) with both Exif data, same filename structure,  do have both behaviour (one is in the "today" section, and the other one in the right day in 2019). 

I was downloading +- 130 photos. 

It also occured for videos.

I tried to have a look at the code, but apparently all it does is downloading the asset and update the file local_id with the one from the asset:

https://github.com/ente-io/ente/blob/7b002c857e446b3692951abc383b9c2933135691/mobile/lib/utils/file_download_util.dart#L219-L227

I am not sure of how the sync process is handling those events but it might be that some events are not processed properly.

### Version

v0.9.65

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by ua741** [comment]
Can you confirm if the original file has exif date?
Usually, when exif date is not present, we try to derive the date from file name or fallback to creation time given by the system.

**Comment by simondubrulle** [comment]
The original file does have EXIF date. It was taken from a OnePlus 5T and has following EXIF (date) keys:

- Image Datetime
- Thumbnail DateTime
- EXIF DateTimeOriginal
- EXIF DateTimeDigitized

I also notice that some (quite a lot) of the files that were selected for download appear with the "not backed up" icon (striked cloud icon) in the "Pictures" folder (and those are the ones which appear in the "Today" section of the Pictures folder, eventhough most of them appear in the right date in the home timeline). Their unique album is "Pictures". As mentionned, I also find photos with EXIF dates in that section.

The rest of the downloaded photos does not have the "not backed up" icon (striked cloud icon) in the "Pictures" folder and they appear in the right date in the pictures folder (and timeline). Their album is not "pictures" but the one(s) which were already set before downloading. There I find photos with and without EXIF dates.

I will setup a test environment where I can mess a bit with the data to try to replicate, and will use the debug app to check if I can see something in the debug logs.

**Comment by simondubrulle** [comment]
@ua741  Is `PhotoManager` shared globally?

Because I see the comment in here which is linked to the issue :

https://github.com/ente-io/ente/blob/b9d6864e224d193d20a7848b66df3742405e8a4d/mobile/lib/utils/file_download_util.dart#L193-L199

And what I see, with extra log info, is that it gets stopped by one file, then directly started by another file (that finished its downloading) while the first has not yet finished its part that should not trigger a sync.

Can this be linked?

**Comment by simondubrulle** [comment]
Thank you for the feedback . I think it is a great suggestion, it should already reduce significantly the likelihood of such events while not introducing big changes 😊
