### ISSUE TITLE
Items in the list are not ordering correctly

### ISSUE THREAD

**Issue by stantios** [ente-io/ente#4297]
### Description

I set my items to order by "Issuer", but it doesn't really work and for some reason the letter "e" is at the bottom rather than near the top.

Here is a screenshot to showcase this issue:
![2024-12-03-19 58 58@2x](https://github.com/user-attachments/assets/c2cc95d6-b3f8-425f-9669-f25f53cbe2db)

### Version

4.1.1

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by Ultrabenosaurus** [comment]
I am also seeing similar behavior in the Android app, version 4.1.1 installed via F-Droid. It is showing GitHub at the top, above Amazon. When I try to take a screenshot the image is just black though, so I can't demonstrate it.

**Comment by ua741** [comment]
The item ordering is case sensitive, that's why you are seeing ebay towards the bottom.

**Comment by Ultrabenosaurus** [comment]
Why is this closed as completed? That is not naturally sorted as humans would ready something. They are still not sorted correctly.
