### ISSUE TITLE
[auth] Add Microsoft icon in Ente Auth

### ISSUE THREAD

**Issue by Adish08** [ente-io/ente#4338]
### Description

Currently, it does not have any icon at all.
![image](https://github.com/user-attachments/assets/fd7d9e1d-3a32-460b-a379-01b195f010db)

### Version

Latest

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by brog-io** [comment]
This will be fixed in the next update, a broken PR went through that broke some icons.
