### ISSUE TITLE
[auth] Add Twitter/X Icon in Ente Auth 

### ISSUE THREAD

**Issue by Adish08** [ente-io/ente#4339]
### Description

Currently, there is no icon for 𝕏.

![image](https://github.com/user-attachments/assets/69e617d8-69c3-4165-9d44-7e31cdec6529)

### Version

Latest

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by brog-io** [comment]
This will be fixed in the next update, a broken PR went through that broke some icons.
