### ISSUE TITLE
Add EA icon

### ISSUE THREAD

**Issue by muhasturk** [ente-io/ente#4347]
### Description

No icon for [EA.](https://www.ea.com/)
![Screenshot 2024-12-08 185310](https://github.com/user-attachments/assets/75945de1-1ea1-445a-b6c6-dd9847711c77)

### Version

4.1.6

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by sv3nnie** [comment]
You can contribute icons yourself. See [ente/auth/docs/adding-icons.md](https://github.com/ente-io/ente/blob/main/auth/docs/adding-icons.md) for instructions.
