### ISSUE TITLE
Missing strings in Crowdin for translating Theme switcher

### ISSUE THREAD

**Issue by JRuedas** [ente-io/ente#4371]
### Description

Although I've been looking for the strings to translate the Theme section of Ente Auth on Crowdin I couldn't find it. I suppose that those strings needs to be added to the app or uploaded to crowdin so the translation can happen.

### Version

v4.1.6

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Linux, Desktop - Windows

**Comment by puTuIvy** [comment]
🦋

**Comment by JRuedas** [comment]
I've seen the missing strings have been added so I'm closing the issue
