### ISSUE TITLE
[Auth] Duplicate entries in iOS and Windows

### ISSUE THREAD

**Issue by rockbrigade** [ente-io/ente#4468]
### Description

All my entries are duplicated, in both iOS and Windows desktop apps. Screenshot provided.
![Screenshot 2024-12-22 135340](https://github.com/user-attachments/assets/0844dd37-7268-4753-8926-60ae3b7eaf5b)

### Version

4.1.6

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS, Desktop - Windows

**Comment by ua741** [comment]
Please use the dedupe option in v4.2.0 to clear these duplicates (Settings -> Data -> Deduplicate)
