### ISSUE TITLE
Automatically logged in without requiring credentials after restarting the computer

### ISSUE THREAD

**Issue by Guuustav** [ente-io/ente#450]
Describe the bug
After restarting my desktop computer. Edge browser opened all the tabs from the previous session and then Auth logged in without asking for login credentials (I don't save any password in browsers either).

Desktop (please complete the following information):
macOS Sonoma 14.3
Microsoft Edge
Versión 121.0.2277.112 (Compilación oficial) (x86_64)

I understand that this behavior is not correct.

**Comment by vishnukvmd** [comment]
Hey, Auth stores all the data in memory on the web. Nothing is written to disk.

So it seems like Edge has reopened while retaining the in-memory state.

What we could do is watch for tab / browser close events, and clear the in-memory state there so that a blank state is what Edge retains.

**Comment by nikunjkumarnakum** [comment]
May be the issue is with the edge browser you are not the only one. [Read this](https://www.theverge.com/24054329/microsoft-edge-automatic-chrome-import-data-feature).
