### ISSUE TITLE
Ente-auth: no icons in version 4.2.1

### ISSUE THREAD

**Issue by rafaelazvdo** [ente-io/ente#4522]
### Description

After installing version 4.2.1, the entries appear without icons and when trying to assign an icon, no icon appears to select even when searching by the issuer's name. I noticed this bug in both the Android and Windows versions. I haven't tested the Linux version, but it probably has the same bug.

### Version

4.2.1

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by vishnukvmd** [comment]
Fixed in https://github.com/ente-io/ente/pull/4524.
