### ISSUE TITLE
ente-auth: please, add custom icon for Caixa

### ISSUE THREAD

**Issue by rafaelazvdo** [ente-io/ente#4531]
### Description

The website http://www.caixa.gov.br/ does not yet have an icon in the ente-auth app. I tried to add the icon to simpleicons but it was not accepted because the website does not have an official link to the svg version of the icon. That's why I added the sgv versions of the icon here so that if possible you can add it to ente-auth.

![Caixa](https://github.com/user-attachments/assets/e63c8d42-b53e-40ff-a9c7-1bb516dcc881)

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android

**Comment by AmanRajSinghMourya** [comment]
If you would like to add your own custom icon, please open a pull-request with the relevant SVG placed within **assets/custom-icons/icons** and add the corresponding entry within **assets/custom-icons/_data/custom-icons.json**.

Guide to add icons:  [https://github.com/ente-io/ente/blob/main/auth/docs/adding-icons.md]()

**Comment by rafaelazvdo** [comment]
> If you would like to add your own custom icon, please open a pull-request with the relevant SVG placed within **assets/custom-icons/icons** and add the corresponding entry within **assets/custom-icons/_data/custom-icons.json**.
> 
> Guide to add icons:  [https://github.com/ente-io/ente/blob/main/auth/docs/adding-icons.md]()

Unfortunately I don't know how to do this.

**Comment by rafaelazvdo** [comment]
The icon looks great on the app, thank you very much for your attention.

**Comment by nacesprin** [comment]
The adding-icons provided guide is broken. This is the new link to [add custom icons](https://github.com/ente-io/ente/blob/531e3362197c7ea1aac606e9e7f6c403670d6b4b/mobile/apps/auth/docs/adding-icons.md) and the [example PR](https://github.com/ente-io/ente/pull/9121)
