### ISSUE TITLE
Mention name of item to delete in confirmation dialogues

### ISSUE THREAD

**Issue by windmueller** [ente-io/ente#459]
**Is your feature request related to a problem? Please describe.**
When deleting an item from ente Auth, there are two confirmation screens: The first asks for my fingerprint, the seconds one is a final confirmation. However, in both dialogues the name of the item I want to delete is missing. So I do not know if I really selected the correct one.

**Describe the solution you'd like**
Both screen should mention the name of the item to delete.

**Comment by 609harsh** [comment]
hi @mnvr please assign this issue to me
