### ISSUE TITLE
[Feature requests] Rename accounts.

### ISSUE THREAD

**Issue by morete** [ente-io/ente#471]
I'd like to be able to rename account after adding them via QR code... When I get multiple accounts on same domain/app like Slack or GitHub, I have work related accounts and private accounts... I'd like to have the ability to rename accounts at any point in time.

I think an "edit" or "rename" option would be nice solution.

I've used the option to enter details manually but typing codes is not ideal when a QR code is available...

**Comment by morete** [comment]
Thank you Vishnu... I completely missed that... Is exactly working as
designed.

**Comment by mrbluecoat** [comment]
Had the same experience. I know there's a popup on initial app install that says you can delete with a swipe left but I didn't remember seeing a reference for _edit_. Perhaps update your FAQ title from `How can I delete codes?` to `How can I edit or delete codes`.
