### ISSUE TITLE
Nightly build 2.0.31 detected as a virus windows 11

### ISSUE THREAD

**Issue by Memememesxy** [ente-io/ente#473]
**Describe the bug**
When installing the app windows detects it as a threat and advises against installing

**To Reproduce**
1. Go to the installer
2. Click on the prompts to install the application
3. See error

**Expected behavior**
The app installs without this warning

**Desktop (please complete the following information):**
Windows 11 Pro (10.0.22621 build 22621) Desktop version 2.0.31

**Comment by vishnukvmd** [comment]
Fixed, see https://github.com/ente-io/ente/issues/658
