### ISSUE TITLE
[Feature Request] Spaces in 7 & 8 digit codes

### ISSUE THREAD

**Issue by Hudzen10** [ente-io/ente#475]
6 digit TOPT codes contain spaces to make it easier to read/recall when manually entering codes, 7 & 8 digit codes do not.

As an example, having come from Authy - their layouts are:
12 **345** 67
123 **45** 678
(n.b. central blocks appear bold in authy desktop app as well which also helps the readability/UX)

Between the phone app and the web interface it is possible to copy-paste in most situations avoiding having to read/remember codes, so is principally a cosmetic/UX issue & does not affect functionality.

EDIT: also just noticed that the web interface does not have spaces in 6 digit codes either.  It would be nice for both the Web and the App UIs to have a consistent look & feel/display layout.

**Comment by 609harsh** [comment]
Hi @ua741 lease assign this issue to me

**Comment by AbhishekSharma55** [comment]
Hi there,

I want to contribute to this project and take on this issue as my first task. Could you please assign it to me? I am excited to work towards resolving it and will keep the team updated on my progress.

Thanks

**Comment by mnvr** [comment]
Hey, that both of you seem up for this, and I'm not sure about how to handle this :) I guess @609harsh is already working on a separate task, so maybe @AbhishekSharma55 you can have a go at this one (I'm just picking randomly!)

**Comment by AbhishekSharma55** [comment]
Hi @mnvr ,

Thanks for looping me in! I'd be more than happy to take a look at this task. I'll dive into it shortly and let you know if I have any questions.

Best regards,
@AbhishekSharma55

**Comment by AbhishekSharma55** [comment]
Hi @mnvr ,

Based on my investigation, it appears that the file that needs to be changed is located at **ente\auth\lib\ui\two_factor_authentication_page.dart.** However, I wanted to confirm with you whether this is indeed the correct path for making the necessary modifications.

Additionally, I'd like to seek clarification on whether the changes should be applied to the **widget body** function within this file.

Your guidance on this matter would be greatly appreciated, as it will help me proceed with the implementation of this feature request accurately.

Thank you for your support and assistance.

**Comment by ua741** [comment]
Let's keep the same font weight.
Please create a PR with the change and screenshot, we can continue the discussions on that.
