### ISSUE TITLE
Request for New Language Translation (and CONTRIBUTING.md link to create an issue don't work as expected)

### ISSUE THREAD

**Issue by ppnplus** [ente-io/ente#512]
### Description

Language: Thai

I'd like to see support for Ente translation in Thai.

Also, the link to create an issue in [CONTRIBUTING.md](https://github.com/ente-io/ente/blob/main/CONTRIBUTING.md#translate) don't work as expected, as clicking the link would require the user to choose from multiple templates instead of opening an issue to add a new language with prefilled text, and the "Feature requests and questions" link in the New Issue page doesn't work (displays a 404 error).

### Version

-

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - iOS

**Comment by mnvr** [comment]
Hey, thanks for reporting these issues! It is likely that these links got broken when the code was moved into the monorepo yesterday, I'm in the middle of fixing this. Will get back soon.

**Comment by mnvr** [comment]
Both the links should be fixed now, please let me know if something is still amiss. Thank you for reporting.

And I've added Thai to the list of languages. ขอบคุณ!
