### ISSUE TITLE
High CPU usage during inference for Magic search

### ISSUE THREAD

**Issue by s38b35M5** [ente-io/ente#645]
The upload process necessarily is a CPU-heavy task as all files are encrypted before upload. 

This should be clearly spelled out in every user-facing doc/how-to/FAQ and perhaps even in the upload procedure in the apps. This would remind the user that they may experience slowdowns (on slower hardware, for instance), and in the case of a Google Takeout upload of many GB, could experience uploads that are CPU-limited and slower than a simple upload of unencrypted data.

**Comment by mnvr** [comment]
The entire ML implementation has been substantially reworked since this was opened, and this particular issue has be resolved. Please reopen a separate issue if you still encounter problems (as it is likely a different issue).
