### ISSUE TITLE
Virustotal scan of Ente Auth Nightly shows that the program connects to a weird IP

### ISSUE THREAD

**Issue by RaduNG** [ente-io/ente#658]
### Description

Hello,

I want an alternative from Authy so the only true PC app 2FA is Ente (almost)

I wanted to try the Ente Auth Nightly,
Virustotal scan of Ente Auth Nightly shows that the program connects to a weird IP that that a crack is connecting to it too.
![image](https://github.com/ente-io/ente/assets/31445781/361a25a4-43a4-4e25-9bb1-f4ec2efb6249)

![image](https://github.com/ente-io/ente/assets/31445781/b9e95914-e0a7-47ae-a6d9-baed84c9ea8c)

It makes me feel untrusty about the legitimate of the project.

Also, I don't understand how in the releases tab are only Ente Auth releases if I am in the overall Ente repository (that contains Ente Photos), it's a bit confusing.

Waiting a response. Thanks.

Reproduce behaviour:
- Download the build
- Scan it on virustotal
- Look at "Relations" -> "Contacted URLs"
- Check the IP on Google
- See viruses that are connecting to the same IP

### Version

nightly

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by RaduNG** [comment]
1. https://www.virustotal.com/gui/file/93993cdf496e37a74bdbd3d0673d5126d98c8ea992979fd19fe8e296239d8ccd/relations
2. https://www.virustotal.com/gui/file/a188ff24aec863479408cee54b337a2fce25b9372ba5573595f7a54b784c65f8/relations

**Comment by arjitc** [comment]
Isn't 172.16.xx.xx a internal IP address range? hence this is most likely connecting to a service within the network or a local-loopback address and not connecting to anything external as such,

Source: https://datatracker.ietf.org/doc/html/rfc1918#section-3

The RFC1918 addresses are:

 - 10.0.0.0/8
 - 172.16.0.0/12
 - 192.168.0.0/16

**Comment by etlweather** [comment]
172.16.x.x is private IP, not internet.

**Comment by brog-io** [comment]
They've recently moved everything to a single repo, that's why you can't see apks for Ente photos.

**Comment by prateekmedia** [comment]
This is totally normal as I confirmed with other flutter apps, the Windows Security scan have given green light to the exe:
![image](https://github.com/ente-io/ente/assets/41370460/7ba0bbd0-a091-4b1e-9cde-bdafece1eb75)
![image](https://github.com/ente-io/ente/assets/41370460/f834294d-2c2f-4ea4-a52e-b9c657116a23)

**Comment by mnvr** [comment]
@RaduNG I think both your queries should be answered.

Your antivirus flagging this seems like a false positive. As @prateekmedia commented above, it seems to passing the tests when submitted to Microsoft. Also, it is a known issue with Flutter apps - Flutter's own SDK runs into false positive virus scans. Some relevant links from the Flutter issue tracker:

- https://github.com/flutter/flutter/issues/46696
- https://github.com/flutter/flutter/issues/139356
- https://github.com/flutter/flutter/issues/58302

As you said, it is not a good first impression - but we just don't why these av programs are flagging us. We would be more than glad if you could help us out though, tell us which part of our code we should change to avoid these false positive flags. 

---

And about the second concern, the releases tab: As @brog-io mention, we're in the process of transitioning to this monorepo, and more and more of the releases will show up there. Already you can find releases of the Ente CLI in this repo's releases (alongwith Ente Auth), and we should have a Ente Photos releases there today, and another Ente Photos Desktop release also being there this week.
