### ISSUE TITLE
Error fetching files: status 524 with err: error code: 524

### ISSUE THREAD

**Issue by creedda** [ente-io/ente#723]
Getting an error when I try and use this with my wife's account.

It looks like it grabs all the metadata fine but errors out when trying to pull photos.

Error fetching files: status 524 with err: error code: 524

```
2024/02/24 16:51:22 Fetching files metadata for album Recents from 2022-12-24 04:47:44.067921 +0000 UTC
[photos-email] 2024/02/24 16:53:02 Error fetching files: status 524 with err: error code: 524
Error syncing account email: status 524 with err: error code: 524
```

I will also reach out via email in case It's something with her account specifically.

**Comment by ua741** [comment]
We have optimized the DB, which resulted in overall reduction in API latency. 

@creedda Please let us know if you are still facing this issue.

**Comment by creedda** [comment]
I appears to be working. I'll put something here if I see this error again.

Thank you!
