### ISSUE TITLE
After running a deduplication, the view won't reflect the removal of photos

### ISSUE THREAD

**Issue by luleyleo** [ente-io/ente#756]
### Description

I did deduplicate my photos, and once I pressed the delete button, it seemed like nothing happened. It still showed all the duplicates and the ones I had selected. When I closed the view and opened it again, no duplicates were found, and they were correctly moved to the trash.

So basically, everything worked just fine, the view just did not reflect it. It would have been nice, if all the deleted duplicates would have also been removed from the deduplication view.

### Version

v1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Linux, Web - Firefox

**Comment by mnvr** [comment]
The desktop app (v1.7.0) with this fix has also been released now. Please reopen if it is still occurring. Thank you.
