### ISSUE TITLE
EXIF location not recognized

### ISSUE THREAD

**Issue by tekmans** [ente-io/ente#759]
### Description

My picture from my smartphone as location in EXIF but ente can't read it
EXIF information
![image](https://github.com/ente-io/ente/assets/1766087/d8b137e7-1e4e-4720-854c-43159cbc566f)
EXIF inside ente app
![image](https://github.com/ente-io/ente/assets/1766087/9dc08cbf-112c-4a54-ad56-b98c278f07cd)

### Version

0.8.64

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android

**Comment by vishnukvmd** [comment]
Hey, could you please verify the EXIF on a tool like [exiftool](https://github.com/exiftool/exiftool) or [jimpl](https://jimpl.com/) (warning: it uploads data to their servers) and let us know if the GPS coordinates are available there?

**Comment by tekmans** [comment]
Here is
![Screenshot 2024-03-08 at 14-43-09 Metadat For IMG_20240308_131501 jpg](https://github.com/ente-io/ente/assets/1766087/688e438b-48d1-4b10-a964-bfd11ca92f12)

**Comment by vishnukvmd** [comment]
Could you please share an affected photo with us (either here or via `support@ente.io`) using an album-link? We'd like to dig in to understand what's going wrong here.

**Comment by perzarys** [comment]
Hi, I'm facing this exact issue on self-hosted Ente 1.2.11. I uploaded my photos through the Android app (Android 15, CalyxOS). "All media access" permission is granted, including "read location from your media collection"; Ente also does not ask for additional permissions. All of my photos have their EXIF location tags show as NaN in Ente, typical "Pin in the ocean" situation. The photos do indeed have EXIF location, I can see them on a world map perfectly fine when opened in piwigo. Any advice, or more info required?

**Comment by mnvr** [comment]
It is likely then that the Exif location is in a different field than the one that the mobile app is looking for.

One option is to try the web/desktop app because
1. The web/desktop app tries a few more combinations of Exif fields that might work better for the specific photos you have (if you're curious - these specific ones - https://github.com/ente-io/ente/blob/49262de9654a2f4dec1b01a088005974ecd13f31/web/packages/gallery/services/exif.ts#L121-L133)
2. Web/desktop also has the "Fix time" option where you can try these fields out without reuploading the photos (Select the "Fix time" option from the action bar).

So you can try that out on 1 or 2 of the photos where the coords were not picked up.

If that doesn't help, then you can open the full exif details of the photos (open the file, open the file info panel, there would be a "view exif" option which shows all the fields) to identify where the coordinates are being stored.

**Comment by perzarys** [comment]
Hi mnvr, thanks for your suggestion. I tried the web app as well, but it makes no  difference. The EXIF data in ente seems to be stripped of the location tags. I see the location of the photo when opening it in exiftool, it has "GPS Latitude" / "GPS Longitude" as well as "GPS Position", but when I check the "View EXIF" option of the same photo in ente web, these tags are all zeroed out:


```
"GPSLatitudeRef":{"id":1,"value":[],"description":"Unknown"},"GPSLatitude":{"id":2,"value":[[0,0],[0,0],[0,0]],"description":null},
"GPSLongitudeRef":{"id":3,"value":[],"description":"Unknown"},"GPSLongitude":{"id":4,"value":[[0,0],[0,0],[0,0]],"description":null},
"GPSAltitudeRef":{"id":5,"value":0,"description":"Sea level"},"GPSAltitude":{"id":6,"value":[0,0],"description":"NaN m"},"
```

**Comment by mnvr** [comment]
Then it seems that the data was not accessible when uploading? Could you try uploading the exact same image that you're exiftool-ing into the web app again (to avoid symlinking to a file which has already been uploaded by the mobile app, you could rename the file)

**Comment by perzarys** [comment]
> Could you try uploading the exact same image that you're exiftool-ing into the web app again (to avoid symlinking to a file which has already been uploaded by the mobile app, you could rename the file)

Did this, and the re-uploaded image (new filename) has the correct location in ente. How would I proceed to do this with my entire gallery I synced with Ente Android, and for the future?

**Comment by mnvr** [comment]
That I feel points to an issue with the metadata permission. You could try uploading the same file again (use a different filename), double checking all the permissions etc (reinstalling the app if needed, or trying on a different device just for the test). If you're double sure that the permissions are correct and the metadata is still not being read, then you should contact support (support@ente.io) with your logs.
