### ISSUE TITLE
F-Droid: anti-feature could be remedied after open sourcing the server

### ISSUE THREAD

**Issue by nazarewk** [ente-io/ente#772]
### Description

Continuing on #3 I've noticed F-Droid marks Ente photos (and the other one) as having anti-feature:
> This app promotes or depends entirely on a non-changeable or non-fRee network service

This does not seem to be true after:
1. https://ente.io/blog/open-sourcing-our-server/
2. closing the issue about pointing the apps to own servers (I think there was GH issue opened, but can't find it right now).

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - FDroid, Web - Firefox

**Comment by vishnukvmd** [comment]
Note: The original anti-feature has been replaced with this one:
>  Tethered to developer server

since we load data (like release info and ML models) from `static.ente.io`.
