### ISSUE TITLE
Notifications for shared items are unreliable

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/ente#799]
Even with "Unrestricted" usage permitted within Battery Settings, the app does not always show notifications for items that have been added to an album the user is a part of.

From [customer feedback](https://discord.com/channels/948937918347608085/1192676327388614717), it sounds like background syncs are running successfully. Which means the issue lies within the invocation of https://github.com/ente-io/photos-app/blob/0dd22e7889ad2458caa7d08ab2cf36ea324fc199/lib/services/remote_sync_service.dart#L965-L971

We're unfortunately having a hard time reproducing this issue, perhaps staring at the code until it confesses is the way to go.

**Comment by vishnukvmd** [comment]
Update from the customer:
> I don't see the "creating notification for"... log at all.
> Logs seem to confirm that background sync successfully pulled in the new items, but that's it. After a successful background sync there is no indication of any notification firing attempt.

Was able to verify this by looking at the logs that were shared.

**Comment by windmueller** [comment]
From my own experience this does not look like a device-specific issue.

I am sharing an album with three people using a Google Pixel 7a. Only one of them gets notified about added items.

**Comment by ua741** [comment]
We recently fixed a bug (v.9.30) that improved notification reliability. I am closing this issue, but if problems persist, we can create another issue, and investigate again.
