### ISSUE TITLE
Ente Authenticator does not open after latest app store update

### ISSUE THREAD

**Issue by Yash-Garg** [ente-io/ente#978]
### Description

App is stuck on the splash screen with ente logo and doesn't move forward.

![image](https://github.com/ente-io/ente/assets/33605526/5e0a13bb-54d4-4a0d-8044-f89be99168f7)

### Version

v2.0.36

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS

**Comment by vishnukvmd** [comment]
Hey, sorry about this, we've submitted a fix to AppStore, the build is in review.

In the meanwhile, if you already have codes backed up (either via Ente or otherwise), please try reinstalling the app.

I'll update this issue once the release is live.

**Comment by vishnukvmd** [comment]
Hey @Yash-Garg, the fix is now live. Please reopen this if it does not fix the issue.
