### ISSUE TITLE
Random currency gets selected when I want to upgrade my payment plan

### ISSUE THREAD

**Issue by luleyleo** [ente-io/ente#980]
### Description

When I open the Subscription plan, I get a random currency each time I press it. It switches between Dollar, Pound and one which I don't even know. I actually want Euros. Can I somehow select which currency I want?

### Version

v1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android, Desktop - Linux, Web - Firefox

**Comment by vishnukvmd** [comment]
Hey, could you please confirm if you're seeing the issue within Ente's subscription screens, or within the payment screen that opens up right after you choose a plan? Thanks!

**Comment by luleyleo** [comment]
I see this, when I open the App (on any platform), open the sidebar, and press on the big green storage quota button.

**Comment by luleyleo** [comment]
On https://ente.io/#pricing it looks correct

**Comment by vishnukvmd** [comment]
Could you please drop a mail to `support@ente.io` from your registered email address? We aren't sure what exactly is going wrong here, will have to dig in to understand better 🙏

**Comment by vishnukvmd** [comment]
Hey @luleyleo, the issue should now be fixed. Please reopen this if otherwise!
