### ISSUE TITLE
Submit PR to FOSS_Photo_Libraries

### ISSUE THREAD

**Issue by meichthys** [ente-io/ente#983]
Now that Ente photos is open sourced, I would like to add it to https://github.com/meichthys/foss_photo_libraries

A PR would be welcomed since there is no demo instance currently and no docker images yet.

**Comment by mnvr** [comment]
Note that there already are docker images that we publish - https://github.com/ente-io/ente/pkgs/container/server

However, to create an standalone demo "appliance", the steps that need to be done are:

1. Create an enhanced version of the existing docker compose file, also including nginx + Ente's web app.
2. Pass the necessary configuration parameters to get the web app to talk to the server within the same cluster.
3. Expose the web app's port as the nginx http.

It is quite straightforward, but I'm not sure when someone from the team will be able to get the time to prioritize this, so meanwhile I thought I'll just outline how it can be done.

**Comment by jo-chemla** [comment]
For those reaching this discussion, 

 - here's a great start for the ente server docker-compose stack: https://github.com/ente-io/ente/blob/main/server/docs/docker.md
  -Regarding self-hosting the photo web-app, see indications [here](https://github.com/ente-io/ente/blob/d8c798e5a242ac7c63c206107509c3d9585c37ce/docs/docs/self-hosting/guides/web-app.md#using-docker), there is no webapp build/docker image already published to ghcr.io. Points to [this discussion](https://github.com/ente-io/ente/discussions/1183) and [this dockerfile](https://help.ente.io/self-hosting/guides/external-s3) while official images are not yet published by ente team. 

My two cents, self-hosters would only need photos and eventually auth to connect to the server.

**Comment by TheRealGramdalf** [comment]
I'm very interested in trying ente out, so I may give it a shot should I get some time. Don't count on it, but I just thought I'd let people know :)

**Comment by iAnonymous3000** [comment]
Hey, we have prepared a draft to add to your comparison table. Please review it and let us know if you need anything. We attempted to modify the entire table, but it was too challenging.

| Feature | Ente |
|:--|:--|
| [Demo](features.md#demo) | 🚧 |
| [Freeness](features.md#freeness) | ✅🔟 |
| [Automatic Mobile Upload](features.md#automatic-mobile-upload) | ✅8️⃣ |
| [Web App](features.md#web-app) | ✅8️⃣ |
| [Android App](features.md#android-app) | ✅8️⃣ |
| [iOS App](features.md#ios-app) | ✅8️⃣ |
| [LivePhotos](features.md#livephotos) | ✅🔟 |
| [Videos](features.md#videos) | ✅6️⃣ |
| [Geolocation/Map](features.md#geolocation/map) | ✅8️⃣ |
| [Discovery](features.md#discovery) | ✅7️⃣ |
| [Existing Folders](features.md#existing-folders) | ✅6️⃣ |
| [Albums](features.md#albums) | ✅🔟 |
| [Slideshow](features.md#slideshow) | 🚧 |
| [Timeline](features.md#timeline) | ✅8️⃣ |
| [Sharing](features.md#sharing) | ✅8️⃣ |
| [Search](features.md#search) | ✅8️⃣ |
| [Duplicate Handling](features.md#duplicate-handling) | ✅7️⃣ |
| [User Defined Tags](features.md#photo-tagging) | 🚧 |
| [Docker Installation](features.md#docker-installation) | ✅7️⃣ |
| [Object/Face Recognition](features.md#object/face-recognition) | ✅6️⃣ |
| [EXIF Data](features.md#exif-data) | ✅7️⃣ |
| [Multiple User Support](features.md#multiple-user-support) | ✅🔟 |
| [Authentication Providers](features.md#authentication-providers) | ❌ |

**Comment by jo-chemla** [comment]
Not exactly sure what are the notation criteria. None of the links are correct, just updated them for what makes sense:

| Feature	| Ente|
|--------|--------|
| [Demo](https://web.ente.io) | ✅ on-premise demo link|
|  [Web App](https://web.ente.io/) | ✅8️⃣ | 
| [Android App](https://play.google.com/store/apps/details?id=io.ente.photos) | ✅8️⃣ | 
| [iOS App](https://apps.apple.com/app/id1542026904) | ✅8️⃣ | 
| [Desktop App](https://ente.io/download/) | ✅8️⃣ | 
| [Docker Installation](features.md#docker-installation) | ✅7️⃣ *
| Authentication Provider: [Ente Auth](https://auth.ente.io/credentials) | ✅ | 


\* ok for server via docker-compose stack, no pre-built container image for photo webapp yet|

**Comment by iAnonymous3000** [comment]
Thanks for the right links! The links I added were not intended to be the actual ones redirecting to the respective resources. It's just a placeholder. For Authentication, they mean OAuth, LDAP, etc.
Reference: https://github.com/meichthys/foss_photo_libraries/blob/main/features.md#authentication-providers

**Comment by iAnonymous3000** [comment]
@meichthys I have opened a PR for this: https://github.com/meichthys/foss_photo_libraries/pull/85

**Comment by vishnukvmd** [comment]
Thanks @iAnonymous3000! @meichthys I'll let you take it forward from here 🙏
