### ISSUE TITLE
[URGENT] Auth PC apps giving wrong codes!!! (while Auth Phone App codes are working fine)

### ISSUE THREAD

**Issue by RaduNG** [ente-io/ente#985]
### Description

Hello,

Wanted to add codes, added them with the mobile app and I restarted the Ente Auth PC Beta app. I have the codes and everything but there are totally different.

For security reasons, I can't show you the proof/codes.
I think this should be very serious in the priority list.

Waiting a response. Thanks.

Reproduce behaviour:
1. Download the mobile app
2. Download the PC app
3. Add a code in the mobile app
4. Restart the PC app (as there isn't instant sync, that's ok.)
5. See that the codes generated are totally different.

### Version

2.0.31

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Desktop - Windows

**Comment by vishnukvmd** [comment]
Could you please confirm that the system time matches that of the one on your mobile?

**Comment by RaduNG** [comment]
I'm sorry, this is my personal problem, my Windows clock is behind 2 minutes.

**Problem solved! Thank you!**

Also, If the codes are different, this means that the codes are not transferred and synced into cloud, only the secret key, and the codes are generated on the device (mobile or phone, separately). Right? That's awesome and add another layer of protection (in my humble and unspecialized opinion).

**Comment by vishnukvmd** [comment]
No worries, glad we could help :)
